"""
전공별 기본 용어 사전 (DEFAULT_GLOSSARY)

== 구조 ==
1. 여러 전공이 공유하는 공통 용어 풀(_POOL_NAME)을 먼저 정의
2. DEFAULT_GLOSSARY의 각 전공 사전은 "공통 풀 + 전공 특화 용어"를 ** 연산자로 병합

== 장점 ==
- 공통 용어 한 곳에서만 관리 → 수정 시 모든 전공에 일괄 반영
- 새 전공 추가 시 풀 조합 + 특화 용어만 작성하면 됨
- 런타임에는 평면 dict로 펼쳐지므로 app.py와 100% 호환

== 사용자 커스텀 ==
사용자가 추가한 용어는 user_glossary.json에 별도 저장됩니다.
"""

# ═══════════════════════════════════════════════════════════════════════
#  공통 용어 풀 (Common Term Pools)
# ═══════════════════════════════════════════════════════════════════════

# ─── 프로그래밍 기본 타입 ───
_PROGRAMMING_TYPES = {
    "int": "int",
    "float": "float",
    "string": "string",
    "boolean": "boolean",
    "list": "list",
    "dict": "dict",
    "tuple": "튜플",
    "array": "배열",
    "None": "None",
    "null": "null",
}

# ─── 컴퓨팅 기초 (CS/DS/AI 공통) ───
_COMPUTING_BASE = {
    "Algorithm": "알고리즘",
    "Data Structure": "자료구조",
    "Variable": "변수",
    "Function": "함수",
    "Class": "클래스",
    "Object": "객체",
    "Method": "메소드",
    "Programming": "프로그래밍",
    "Code": "코드",
    "Debugging": "디버깅",
    "Compiler": "컴파일러",
    "Database": "데이터베이스",
    "SQL": "SQL(구조적 질의 언어)",
    "API": "API(응용 프로그래밍 인터페이스)",
    "Framework": "프레임워크",
    "Library": "라이브러리",
    "Time Complexity": "시간 복잡도",
    "Space Complexity": "공간 복잡도",
    "Pipeline": "파이프라인",
}

# ─── 통계 기초 ───
_STATISTICS_BASE = {
    "Statistics": "통계학",
    "Mean": "평균",
    "Median": "중앙값",
    "Mode": "최빈값",
    "Variance": "분산",
    "Standard Deviation": "표준편차",
    "Correlation": "상관관계",
    "Covariance": "공분산",
    "Regression": "회귀",
    "Probability": "확률",
    "Hypothesis": "가설",
    "Hypothesis Testing": "가설 검정",
    "P-value": "p-값",
    "Confidence Interval": "신뢰 구간",
    "Sample": "표본",
    "Population": "모집단",
    "Distribution": "분포",
    "Normal Distribution": "정규 분포",
    "Random Variable": "확률 변수",
    "Expected Value": "기댓값",
    "Sampling": "샘플링",
    "Bias": "편향",
    "Linear Regression": "선형 회귀",
    "Logistic Regression": "로지스틱 회귀",
}

# ─── 머신러닝 기초 (DS/AI 공통) ───
_ML_BASE = {
    "Machine Learning": "머신러닝",
    "Deep Learning": "딥러닝",
    "Neural Network": "신경망",
    "Training": "학습",
    "Model": "모델",
    "Inference": "추론",
    "Overfitting": "과적합",
    "Underfitting": "과소적합",
    "Feature": "피처",
    "Classification": "분류",
    "Clustering": "군집화",
    "Cross-validation": "교차 검증",
    "Hyperparameter": "하이퍼파라미터",
    "Parameter": "파라미터",
    "Gradient Descent": "경사 하강법",
    "Loss Function": "손실 함수",
    "Activation Function": "활성화 함수",
    "Embedding": "임베딩",
    "Transfer Learning": "전이 학습",
    "Confusion Matrix": "혼동 행렬",
    "Precision": "정밀도",
    "Recall": "재현율",
    "F1 Score": "F1 점수",
    "ROC Curve": "ROC 곡선",
    "AUC": "AUC(곡선 아래 면적)",
    "Accuracy": "정확도",
    "Decision Tree": "의사결정 트리",
    "Random Forest": "랜덤 포레스트",
    "Ensemble": "앙상블",
    "Boosting": "부스팅",
    "Optimizer": "최적화기",
    "Epoch": "에포크",
    "Batch Size": "배치 크기",
    "Learning Rate": "학습률",
    "Regularization": "정규화(규제)",
    "Dropout": "드롭아웃",
}

# ─── 데이터 전처리 (DS/AI 공통) ───
_DATA_PREP = {
    "Data Preprocessing": "데이터 전처리",
    "Data Wrangling": "데이터 정제",
    "Exploratory Data Analysis": "탐색적 데이터 분석",
    "Outlier": "이상치",
    "Missing Value": "결측값",
    "Normalization": "정규화",
    "Standardization": "표준화",
    "Feature Engineering": "피처 엔지니어링",
    "Feature Selection": "피처 선택",
    "Dimensionality Reduction": "차원 축소",
    "Label Encoding": "레이블 인코딩",
    "One-Hot Encoding": "원핫 인코딩",
    "Training Set": "훈련 세트",
    "Validation Set": "검증 세트",
    "Test Set": "테스트 세트",
    "Structured Data": "정형 데이터",
    "Unstructured Data": "비정형 데이터",
}

# ─── 물리/역학 (물리/기계공학 공통) ───
_PHYSICS_MECHANICS = {
    "Force": "힘",
    "Mass": "질량",
    "Energy": "에너지",
    "Work": "일",
    "Power": "일률",
    "Velocity": "속도",
    "Acceleration": "가속도",
    "Momentum": "운동량",
    "Friction": "마찰",
    "Torque": "토크",
    "Pressure": "압력",
    "Density": "밀도",
    "Newton's Laws": "뉴턴의 법칙",
    "Equilibrium": "평형",
    "Moment of Inertia": "관성 모멘트",
    "Angular Velocity": "각속도",
    "Kinetic Energy": "운동 에너지",
    "Potential Energy": "위치 에너지",
    "Conservation of Energy": "에너지 보존 법칙",
    "Vibration": "진동",
    "Resonance": "공진",
}

# ─── 열역학 ───
_THERMODYNAMICS = {
    "Thermodynamics": "열역학",
    "Temperature": "온도",
    "Heat": "열",
    "Entropy": "엔트로피",
    "Enthalpy": "엔탈피",
    "Specific Heat": "비열",
    "Heat Transfer": "열전달",
    "Conduction": "전도",
    "Convection": "대류",
    "Radiation": "복사",
    "Thermal Efficiency": "열효율",
}

# ─── 유체역학 ───
_FLUID = {
    "Fluid Mechanics": "유체역학",
    "Viscosity": "점도",
    "Reynolds Number": "레이놀즈 수",
    "Turbulence": "난류",
    "Laminar Flow": "층류",
    "Bernoulli's Equation": "베르누이 방정식",
}

# ─── 화학 기초 ───
_CHEMISTRY_BASE = {
    "Reaction": "반응",
    "Catalyst": "촉매",
    "Reaction Rate": "반응 속도",
    "Activation Energy": "활성화 에너지",
    "Exothermic": "발열",
    "Endothermic": "흡열",
    "Oxidation": "산화",
    "Reduction": "환원",
    "Concentration": "농도",
    "Solvent": "용매",
    "Solute": "용질",
    "pH": "수소이온농도",
    "Acid": "산",
    "Base": "염기",
    "Molecule": "분자",
    "Atom": "원자",
    "Compound": "화합물",
    "Diffusion": "확산",
}

# ─── 생명/분자 ───
_BIO_MOLECULAR = {
    "DNA": "DNA(디옥시리보핵산)",
    "RNA": "RNA(리보핵산)",
    "Protein": "단백질",
    "Enzyme": "효소",
    "Gene": "유전자",
    "Cell": "세포",
    "Mutation": "돌연변이",
    "Antibody": "항체",
    "Antigen": "항원",
    "Vaccine": "백신",
    "Amino Acid": "아미노산",
    "Genome": "유전체",
    "Chromosome": "염색체",
}

# ─── 임상/의학 기초 ───
_MEDICAL_BASIC = {
    "Diagnosis": "진단",
    "Treatment": "치료",
    "Symptom": "증상",
    "Prognosis": "예후",
    "Infection": "감염",
    "Inflammation": "염증",
    "Immunity": "면역",
    "Surgery": "수술",
    "Anesthesia": "마취",
    "Antibiotic": "항생제",
    "Vital Signs": "활력 징후",
    "Blood Pressure": "혈압",
    "Pulse": "맥박",
    "Side Effect": "부작용",
    "Allergy": "알레르기",
    "Clinical Trial": "임상 시험",
    "Patient": "환자",
    "Informed Consent": "사전 동의",
    "Palliative Care": "완화 치료",
    "Chronic Disease": "만성 질환",
    "Acute Disease": "급성 질환",
    "Dosage": "용량",
    "Pharmacology": "약리학",
}

# ─── 경영/사업 기초 ───
_BUSINESS_BASE = {
    "Strategy": "전략",
    "Management": "경영",
    "Stakeholder": "이해관계자",
    "ROI": "투자 수익률",
    "KPI": "핵심 성과 지표",
    "Revenue": "매출",
    "Profit": "이익",
    "Cost": "비용",
    "Investment": "투자",
    "Risk Management": "위험 관리",
    "Market Share": "시장 점유율",
    "Competitive Advantage": "경쟁 우위",
    "Innovation": "혁신",
    "Globalization": "세계화",
    "Sustainability": "지속 가능성",
    "CRM": "고객 관계 관리",
    "B2B": "기업 간 거래",
    "B2C": "기업-소비자 거래",
    "SWOT Analysis": "SWOT 분석",
    "Business Model": "비즈니스 모델",
    "Value Chain": "가치 사슬",
    "Corporate Governance": "기업 지배구조",
    "Merger": "합병",
    "Acquisition": "인수",
}

# ─── 마케팅 ───
_MARKETING_BASE = {
    "Brand": "브랜드",
    "Target Market": "목표 시장",
    "Positioning": "포지셔닝",
    "Marketing Mix": "마케팅 믹스",
    "Advertising": "광고",
    "Consumer Behavior": "소비자 행동",
    "Customer Lifetime Value": "고객 생애 가치",
    "Conversion Rate": "전환율",
    "Brand Equity": "브랜드 자산",
    "Market Segmentation": "시장 세분화",
    "Brand Awareness": "브랜드 인지도",
}

# ─── 회계/재무 ───
_ACCOUNTING_BASE = {
    "Asset": "자산",
    "Liability": "부채",
    "Equity": "자본",
    "Balance Sheet": "대차대조표",
    "Income Statement": "손익계산서",
    "Cash Flow": "현금 흐름",
    "Depreciation": "감가상각",
    "Audit": "감사",
    "Tax": "세금",
    "Working Capital": "운전 자본",
    "Gross Profit": "매출 총이익",
    "Net Income": "순이익",
    "EBITDA": "EBITDA(세전 이자·세금·감가상각 전 이익)",
}

# ─── 디자인 기초 ───
_DESIGN_BASE = {
    "Composition": "구성",
    "Color Palette": "색상 팔레트",
    "Hue": "색상",
    "Saturation": "채도",
    "Texture": "질감",
    "Pattern": "패턴",
    "Proportion": "비례",
    "Symmetry": "대칭",
    "Asymmetry": "비대칭",
    "Balance": "균형",
    "Contrast": "대비",
    "Sketch": "스케치",
    "Prototype": "프로토타입",
    "Aesthetics": "미학",
    "Typography": "타이포그래피",
    "Negative Space": "여백",
    "Layout": "레이아웃",
    "Rendering": "렌더링",
}

# ─── 정치/사회 ───
_POLITICS_SOCIETY = {
    "Democracy": "민주주의",
    "Authoritarianism": "권위주의",
    "Sovereignty": "주권",
    "Ideology": "이데올로기",
    "Hegemony": "헤게모니",
    "Civil Society": "시민사회",
    "Human Rights": "인권",
    "Nationalism": "민족주의",
    "Liberalism": "자유주의",
    "Conservatism": "보수주의",
    "Capitalism": "자본주의",
    "Socialism": "사회주의",
    "Multiculturalism": "다문화주의",
    "Foreign Policy": "외교 정책",
    "Public Policy": "공공 정책",
}

# ─── 연구/학술 기초 ───
_RESEARCH_BASE = {
    "Research": "연구",
    "Theory": "이론",
    "Methodology": "방법론",
    "Qualitative Research": "질적 연구",
    "Quantitative Research": "양적 연구",
    "Case Study": "사례 연구",
    "Literature Review": "문헌 검토",
    "Survey": "설문 조사",
    "Interview": "면접",
}


# ═══════════════════════════════════════════════════════════════════════
#  전공별 사전 (DEFAULT_GLOSSARY)
# ═══════════════════════════════════════════════════════════════════════

DEFAULT_GLOSSARY = {

    # ─────────────────────────────────────────────────────────────────
    # 이과 (Science & Engineering)
    # ─────────────────────────────────────────────────────────────────

    "Data Science": {
        **_PROGRAMMING_TYPES,
        **_COMPUTING_BASE,
        **_STATISTICS_BASE,
        **_ML_BASE,
        **_DATA_PREP,
        "Data Science": "데이터사이언스",
        "Backpropagation": "역전파",
        "Principal Component Analysis": "주성분 분석",
        "Insights": "인사이트",
        "Multi-disciplinary": "다학제",
        "Domain": "도메인",
        "Support Vector Machine": "서포트 벡터 머신",
        "K-Nearest Neighbor": "K-최근접 이웃",
        "Naive Bayes": "나이브 베이즈",
        "Histogram": "히스토그램",
        "Scatter Plot": "산점도",
        "Box Plot": "박스 플롯",
        "Heatmap": "히트맵",
        "Time Series": "시계열",
        "Seasonality": "계절성",
        "Trend": "추세",
        "Anomaly Detection": "이상 탐지",
        "Data Lake": "데이터 레이크",
        "Data Warehouse": "데이터 웨어하우스",
        "ETL": "ETL(추출·변환·적재)",
        "Big Data": "빅데이터",
        "Hadoop": "하둡",
        "Spark": "스파크",
        "NoSQL": "NoSQL(비관계형 데이터베이스)",
        "Imbalanced Dataset": "불균형 데이터셋",
        "SMOTE": "SMOTE(합성 오버샘플링)",
        "Mean Absolute Error": "평균 절대 오차",
        "Mean Squared Error": "평균 제곱 오차",
        "R-squared": "결정계수",
        "Data Augmentation": "데이터 증강",
        "Synthetic Data": "합성 데이터",
        "Model Interpretability": "모델 해석 가능성",
        "Feature Importance": "피처 중요도",
    },

    "Artificial Intelligence Engineering": {
        **_PROGRAMMING_TYPES,
        **_COMPUTING_BASE,
        **_STATISTICS_BASE,
        **_ML_BASE,
        **_DATA_PREP,
        "Artificial Intelligence": "인공지능",
        "Natural Language Processing": "자연어 처리",
        "Computer Vision": "컴퓨터 비전",
        "Reinforcement Learning": "강화학습",
        "Transformer": "트랜스포머",
        "Attention Mechanism": "어텐션 메커니즘",
        "Generative Model": "생성 모델",
        "Prompt Engineering": "프롬프트 엔지니어링",
        "Fine-tuning": "파인튜닝",
        "Pre-trained Model": "사전 학습 모델",
        "Object Detection": "객체 탐지",
        "Semantic Segmentation": "의미론적 분할",
        "Speech Recognition": "음성 인식",
        "Text Generation": "텍스트 생성",
        "Tokenization": "토크나이제이션",
        "Knowledge Graph": "지식 그래프",
        "Reward Function": "보상 함수",
        "Hallucination": "환각(오류 생성)",
        "Large Language Model": "거대 언어 모델",
        "Multimodal": "멀티모달",
        "Zero-shot Learning": "제로샷 학습",
        "Few-shot Learning": "퓨샷 학습",
        "Chain of Thought": "사고의 연쇄",
        "Retrieval-Augmented Generation": "검색 증강 생성",
        "Vector Database": "벡터 데이터베이스",
        "Convolutional Neural Network": "합성곱 신경망",
        "Recurrent Neural Network": "순환 신경망",
        "Long Short-Term Memory": "장단기 메모리",
        "Generative Adversarial Network": "생성적 적대 신경망",
        "Diffusion Model": "확산 모델",
        "Image Classification": "이미지 분류",
        "Named Entity Recognition": "개체명 인식",
        "Sentiment Analysis": "감성 분석",
        "Machine Translation": "기계 번역",
        "Text Summarization": "텍스트 요약",
        "Question Answering": "질의응답",
        "Chatbot": "챗봇",
        "Word Embedding": "단어 임베딩",
        "Cosine Similarity": "코사인 유사도",
        "Beam Search": "빔 탐색",
        "Temperature Sampling": "온도 샘플링",
        "Quantization": "양자화",
        "Knowledge Distillation": "지식 증류",
        "Federated Learning": "연합 학습",
        "Edge AI": "엣지 AI",
        "Explainable AI": "설명 가능한 AI",
        "MLOps": "MLOps(머신러닝 운영)",
        "AutoML": "자동 머신러닝",
        "Self-supervised Learning": "자기지도 학습",
        "RLHF": "인간 피드백 강화학습",
        "Positional Encoding": "위치 인코딩",
        "Layer Normalization": "레이어 정규화",
        "Softmax": "소프트맥스",
        "Cross-entropy Loss": "교차 엔트로피 손실",
    },

    "Statistics": {
        **_PROGRAMMING_TYPES,
        **_STATISTICS_BASE,
        "Descriptive Statistics": "기술 통계",
        "Inferential Statistics": "추론 통계",
        "Skewness": "왜도",
        "Kurtosis": "첨도",
        "Quartile": "사분위수",
        "Percentile": "백분위수",
        "Interquartile Range": "사분위 범위",
        "Z-score": "Z-점수",
        "T-test": "T-검정",
        "ANOVA": "분산 분석",
        "Chi-square Test": "카이제곱 검정",
        "Mann-Whitney U Test": "맨휘트니 U 검정",
        "Wilcoxon Test": "윌콕슨 검정",
        "Kruskal-Wallis Test": "크루스칼-월리스 검정",
        "Pearson Correlation": "피어슨 상관계수",
        "Spearman Correlation": "스피어만 상관계수",
        "Multiple Regression": "다중 회귀",
        "Polynomial Regression": "다항 회귀",
        "Maximum Likelihood Estimation": "최대 우도 추정",
        "Method of Moments": "적률법",
        "Bayesian Inference": "베이즈 추론",
        "Posterior Distribution": "사후 분포",
        "Prior Distribution": "사전 분포",
        "Markov Chain Monte Carlo": "마르코프 체인 몬테카를로",
        "Bootstrap": "부트스트랩",
        "Jackknife": "잭나이프",
        "Type I Error": "1종 오류",
        "Type II Error": "2종 오류",
        "Statistical Power": "검정력",
        "Effect Size": "효과 크기",
        "Central Limit Theorem": "중심 극한 정리",
        "Law of Large Numbers": "큰 수의 법칙",
        "Probability Density Function": "확률 밀도 함수",
        "Cumulative Distribution Function": "누적 분포 함수",
        "Binomial Distribution": "이항 분포",
        "Poisson Distribution": "푸아송 분포",
        "Exponential Distribution": "지수 분포",
        "Chi-square Distribution": "카이제곱 분포",
        "F-distribution": "F-분포",
        "T-distribution": "t-분포",
        "Time Series Analysis": "시계열 분석",
        "ARIMA": "ARIMA 모형",
        "Stationarity": "정상성",
        "Autocorrelation": "자기상관",
        "Survival Analysis": "생존 분석",
        "Kaplan-Meier": "카플란-마이어 곡선",
        "Cox Regression": "콕스 회귀",
        "Experimental Design": "실험 설계",
        "Random Sampling": "무작위 추출",
        "Stratified Sampling": "층화 추출",
    },

    "Computer Science": {
        **_PROGRAMMING_TYPES,
        **_COMPUTING_BASE,
        "Recursion": "재귀",
        "Stack": "스택",
        "Queue": "큐",
        "Linked List": "연결 리스트",
        "Binary Tree": "이진 트리",
        "Graph": "그래프",
        "Sorting": "정렬",
        "Searching": "탐색",
        "Hashing": "해싱",
        "Dynamic Programming": "동적 프로그래밍",
        "Greedy Algorithm": "그리디 알고리즘",
        "Divide and Conquer": "분할 정복",
        "Operating System": "운영체제",
        "Process": "프로세스",
        "Thread": "스레드",
        "Deadlock": "교착 상태",
        "Semaphore": "세마포어",
        "Virtual Memory": "가상 메모리",
        "Cache": "캐시",
        "Network": "네트워크",
        "Protocol": "프로토콜",
        "Encryption": "암호화",
        "Object-Oriented Programming": "객체지향 프로그래밍",
        "Inheritance": "상속",
        "Polymorphism": "다형성",
        "Encapsulation": "캡슐화",
        "Abstraction": "추상화",
        "Version Control": "버전 관리",
        "Interpreter": "인터프리터",
        "Refactoring": "리팩터링",
        "Binary Search": "이진 탐색",
        "Merge Sort": "병합 정렬",
        "Quick Sort": "퀵 정렬",
        "Breadth-First Search": "너비 우선 탐색",
        "Depth-First Search": "깊이 우선 탐색",
        "Dijkstra Algorithm": "다익스트라 알고리즘",
        "Hash Table": "해시 테이블",
        "Priority Queue": "우선순위 큐",
        "Heap": "힙",
        "Trie": "트라이",
        "Pointer": "포인터",
        "Garbage Collection": "가비지 컬렉션",
        "Concurrency": "동시성",
        "Parallelism": "병렬성",
        "Mutex": "뮤텍스",
        "Race Condition": "경쟁 조건",
        "Scheduling": "스케줄링",
        "File System": "파일 시스템",
        "Socket": "소켓",
        "TCP/IP": "TCP/IP 프로토콜",
        "HTTP": "HTTP(하이퍼텍스트 전송 프로토콜)",
        "REST API": "REST API",
        "JSON": "JSON(자바스크립트 객체 표기법)",
        "Cloud Computing": "클라우드 컴퓨팅",
        "Microservices": "마이크로서비스",
        "Docker": "도커(컨테이너 플랫폼)",
        "Kubernetes": "쿠버네티스",
        "CI/CD": "CI/CD(지속적 통합/배포)",
        "Unit Test": "단위 테스트",
        "Design Pattern": "디자인 패턴",
        "MVC": "MVC(모델-뷰-컨트롤러)",
        "Frontend": "프론트엔드",
        "Backend": "백엔드",
        "Repository": "저장소",
        "Branch": "브랜치",
        "Merge": "병합",
        "Agile": "애자일",
        "Scrum": "스크럼",
        "Load Balancing": "부하 분산",
    },

    "Information Security": {
        **_PROGRAMMING_TYPES,
        **_COMPUTING_BASE,
        "Information Security": "정보보안",
        "Cybersecurity": "사이버 보안",
        "Confidentiality": "기밀성",
        "Integrity": "무결성",
        "Availability": "가용성",
        "CIA Triad": "정보보안 3원칙(CIA)",
        "Encryption": "암호화",
        "Decryption": "복호화",
        "Symmetric Encryption": "대칭 키 암호화",
        "Asymmetric Encryption": "비대칭 키 암호화",
        "Public Key": "공개 키",
        "Private Key": "개인 키",
        "RSA": "RSA 알고리즘",
        "AES": "AES(고급 암호화 표준)",
        "Hash Function": "해시 함수",
        "SHA": "SHA(보안 해시 알고리즘)",
        "Digital Signature": "전자 서명",
        "Certificate": "인증서",
        "SSL/TLS": "SSL/TLS(전송 계층 보안)",
        "VPN": "가상 사설망",
        "Firewall": "방화벽",
        "IDS": "침입 탐지 시스템",
        "IPS": "침입 방지 시스템",
        "Malware": "악성 코드",
        "Virus": "바이러스",
        "Worm": "웜",
        "Trojan Horse": "트로이 목마",
        "Ransomware": "랜섬웨어",
        "Spyware": "스파이웨어",
        "Phishing": "피싱",
        "Social Engineering": "사회공학적 공격",
        "SQL Injection": "SQL 인젝션",
        "Cross-Site Scripting": "크로스 사이트 스크립팅(XSS)",
        "Buffer Overflow": "버퍼 오버플로",
        "DDoS Attack": "분산 서비스 거부 공격",
        "Man-in-the-Middle": "중간자 공격",
        "Zero-Day Vulnerability": "제로데이 취약점",
        "Penetration Testing": "모의 침투 테스트",
        "Vulnerability Assessment": "취약점 평가",
        "Risk Assessment": "위험 평가",
        "Authentication": "인증",
        "Authorization": "권한 부여",
        "Multi-factor Authentication": "다단계 인증",
        "Single Sign-On": "통합 인증",
        "Access Control": "접근 제어",
        "Role-Based Access Control": "역할 기반 접근 제어",
        "Security Audit": "보안 감사",
        "Forensics": "디지털 포렌식",
        "Incident Response": "사고 대응",
        "SIEM": "보안 정보 이벤트 관리",
        "SOC": "보안 관제 센터",
        "Threat Intelligence": "위협 인텔리전스",
        "Blockchain Security": "블록체인 보안",
        "GDPR": "개인정보보호규정",
        "ISO 27001": "정보보안 국제 표준",
        "Bug Bounty": "버그 바운티",
        "Red Team": "레드팀",
        "Blue Team": "블루팀",
    },

    "Electrical Engineering": {
        **_PROGRAMMING_TYPES,
        "Circuit": "회로",
        "Voltage": "전압",
        "Current": "전류",
        "Resistance": "저항",
        "Capacitor": "커패시터",
        "Inductor": "인덕터",
        "Transistor": "트랜지스터",
        "Semiconductor": "반도체",
        "Diode": "다이오드",
        "Integrated Circuit": "집적 회로",
        "Microcontroller": "마이크로컨트롤러",
        "Signal Processing": "신호 처리",
        "Analog": "아날로그",
        "Digital": "디지털",
        "Frequency": "주파수",
        "Amplitude": "진폭",
        "Impedance": "임피던스",
        "Power Factor": "역률",
        "Transformer": "변압기",
        "Relay": "릴레이",
        "Feedback": "피드백",
        "PID Controller": "PID 제어기",
        "Oscilloscope": "오실로스코프",
        "PCB": "인쇄 회로 기판",
        "Ohm's Law": "옴의 법칙",
        "Kirchhoff's Voltage Law": "키르히호프 전압 법칙",
        "Kirchhoff's Current Law": "키르히호프 전류 법칙",
        "AC Circuit": "교류 회로",
        "DC Circuit": "직류 회로",
        "Rectifier": "정류기",
        "Inverter": "인버터",
        "Amplifier": "증폭기",
        "Operational Amplifier": "연산 증폭기",
        "Filter": "필터",
        "Low-pass Filter": "저역통과 필터",
        "High-pass Filter": "고역통과 필터",
        "Bandwidth": "대역폭",
        "Phase": "위상",
        "Resonance": "공진",
        "Logic Gate": "논리 게이트",
        "Flip-flop": "플립플롭",
        "Multiplexer": "멀티플렉서",
        "ADC": "아날로그-디지털 변환기",
        "DAC": "디지털-아날로그 변환기",
        "MOSFET": "금속산화물 반도체 전계효과 트랜지스터",
        "LED": "발광 다이오드",
        "Electromagnetic Field": "전자기장",
        "Faraday's Law": "패러데이 법칙",
        "Maxwell's Equations": "맥스웰 방정식",
        "Transmission Line": "전송선",
        "Antenna": "안테나",
        "Modulation": "변조",
        "Fourier Transform": "푸리에 변환",
        "Laplace Transform": "라플라스 변환",
        "Transfer Function": "전달 함수",
        "Bode Plot": "보드 선도",
        "Noise": "잡음",
        "Signal-to-Noise Ratio": "신호 대 잡음비",
        "Embedded System": "임베디드 시스템",
        "FPGA": "현장 프로그래머블 게이트 어레이",
        "VHDL": "VHDL(하드웨어 기술 언어)",
        "Verilog": "베릴로그",
        "Power Electronics": "전력 전자",
        "Smart Grid": "스마트 그리드",
    },

    "Mechanical Engineering": {
        **_PHYSICS_MECHANICS,
        **_THERMODYNAMICS,
        **_FLUID,
        "Statics": "정역학",
        "Dynamics": "동역학",
        "Stress": "응력",
        "Strain": "변형률",
        "Kinematics": "운동학",
        "Material Science": "재료 공학",
        "Fatigue": "피로 파괴",
        "Yield Strength": "항복 강도",
        "Hardness": "경도",
        "Manufacturing": "제조",
        "CNC": "CNC(수치 제어 공작기계)",
        "CAD": "CAD(컴퓨터 지원 설계)",
        "Gear": "기어",
        "Bearing": "베어링",
        "Free Body Diagram": "자유 물체도",
        "Work-Energy Theorem": "일-에너지 정리",
        "Efficiency": "효율",
        "Drag Force": "항력",
        "Lift Force": "양력",
        "Carnot Cycle": "카르노 사이클",
        "Heat Engine": "열기관",
        "Rankine Cycle": "랭킨 사이클",
        "Refrigeration Cycle": "냉동 사이클",
        "Tensile Strength": "인장 강도",
        "Compressive Strength": "압축 강도",
        "Shear Stress": "전단 응력",
        "Elastic Modulus": "탄성 계수",
        "Poisson's Ratio": "푸아송 비",
        "Plastic Deformation": "소성 변형",
        "Creep": "크리프",
        "Fracture Mechanics": "파괴 역학",
        "Corrosion": "부식",
        "Alloy": "합금",
        "Composite Material": "복합 재료",
        "Casting": "주조",
        "Forging": "단조",
        "Welding": "용접",
        "Machining": "절삭 가공",
        "Tolerance": "공차",
        "Spring Constant": "용수철 상수",
        "Damping": "감쇠",
        "Natural Frequency": "고유 진동수",
        "Finite Element Analysis": "유한 요소 해석",
        "Quality Control": "품질 관리",
        "3D Printing": "3D 프린팅",
        "Hydraulics": "유압",
        "Pneumatics": "공압",
        "Shaft": "축",
        "Pulley": "풀리",
        "Lubrication": "윤활",
    },

    "Chemical Engineering": {
        **_THERMODYNAMICS,
        **_FLUID,
        **_CHEMISTRY_BASE,
        "Reaction Engineering": "반응 공학",
        "Mass Transfer": "물질 전달",
        "Heat Exchanger": "열교환기",
        "Distillation": "증류",
        "Absorption": "흡수",
        "Stoichiometry": "화학량론",
        "Reactor": "반응기",
        "Yield": "수율",
        "Selectivity": "선택성",
        "Phase Diagram": "상태도",
        "Polymer": "고분자",
        "Separation": "분리",
        "Batch Reactor": "회분식 반응기",
        "Continuous Stirred Tank Reactor": "연속 교반 탱크 반응기",
        "Plug Flow Reactor": "플러그 흐름 반응기",
        "Residence Time": "체류 시간",
        "Conversion": "전환율",
        "Rate Law": "반응 속도식",
        "Arrhenius Equation": "아레니우스 방정식",
        "Mass Balance": "물질 수지",
        "Energy Balance": "에너지 수지",
        "Steady State": "정상 상태",
        "Packed Bed": "충전층",
        "Fluidized Bed": "유동층",
        "Reflux Ratio": "환류비",
        "Condenser": "응축기",
        "Extraction": "추출",
        "Crystallization": "결정화",
        "Filtration": "여과",
        "Evaporation": "증발",
        "Adsorption": "흡착",
        "Membrane Separation": "막 분리",
        "Reverse Osmosis": "역삼투",
        "Electrochemistry": "전기화학",
        "Gibbs Free Energy": "깁스 자유 에너지",
        "Vapor-Liquid Equilibrium": "기액 평형",
        "Process Control": "공정 제어",
        "Scale-up": "규모 확대",
        "Pilot Plant": "파일럿 플랜트",
        "Critical Point": "임계점",
        "Surfactant": "계면활성제",
        "Green Chemistry": "녹색 화학",
        "Waste Treatment": "폐기물 처리",
    },

    "Civil Engineering": {
        **_PHYSICS_MECHANICS,
        **_FLUID,
        "Civil Engineering": "토목공학",
        "Structural Engineering": "구조 공학",
        "Geotechnical Engineering": "지반 공학",
        "Hydraulic Engineering": "수리 공학",
        "Transportation Engineering": "교통 공학",
        "Construction Management": "건설 관리",
        "Surveying": "측량",
        "Concrete": "콘크리트",
        "Reinforced Concrete": "철근 콘크리트",
        "Prestressed Concrete": "프리스트레스 콘크리트",
        "Steel Structure": "철골 구조",
        "Bridge": "교량",
        "Tunnel": "터널",
        "Dam": "댐",
        "Highway": "고속도로",
        "Railway": "철도",
        "Airport Engineering": "공항 공학",
        "Foundation": "기초",
        "Pile Foundation": "말뚝 기초",
        "Shallow Foundation": "얕은 기초",
        "Deep Foundation": "깊은 기초",
        "Soil Mechanics": "토질 역학",
        "Rock Mechanics": "암반 역학",
        "Slope Stability": "사면 안정성",
        "Earth Pressure": "토압",
        "Bearing Capacity": "지지력",
        "Settlement": "침하",
        "Consolidation": "압밀",
        "Permeability": "투수성",
        "Compaction": "다짐",
        "Reinforcement": "보강",
        "Beam": "보",
        "Column": "기둥",
        "Slab": "슬래브",
        "Frame": "골조",
        "Truss": "트러스",
        "Arch": "아치",
        "Cable": "케이블",
        "Suspension Bridge": "현수교",
        "Cable-stayed Bridge": "사장교",
        "Load": "하중",
        "Dead Load": "고정 하중",
        "Live Load": "활하중",
        "Seismic Load": "지진 하중",
        "Wind Load": "풍하중",
        "Shear Force": "전단력",
        "Bending Moment": "휨 모멘트",
        "Axial Force": "축력",
        "Stress Analysis": "응력 해석",
        "Earthquake Engineering": "지진 공학",
        "Seismic Design": "내진 설계",
        "Vibration Analysis": "진동 해석",
        "Hydrology": "수문학",
        "Hydraulics": "수리학",
        "Open Channel Flow": "개수로 흐름",
        "Pipe Flow": "관수로 흐름",
        "Sewerage": "하수도",
        "Water Supply": "상수도",
        "Stormwater": "우수",
        "Pavement": "포장",
        "Asphalt": "아스팔트",
        "Traffic Flow": "교통 흐름",
        "Construction Material": "건설 재료",
        "Cement": "시멘트",
        "Aggregate": "골재",
        "Mortar": "모르타르",
        "Curing": "양생",
        "Site Investigation": "현장 조사",
        "Geographic Information System": "지리정보시스템(GIS)",
        "BIM": "건물 정보 모델링",
        "Sustainable Construction": "지속 가능 건설",
    },

    "Environmental Engineering": {
        **_CHEMISTRY_BASE,
        "Environmental Engineering": "환경공학",
        "Sustainability": "지속 가능성",
        "Pollution": "오염",
        "Air Pollution": "대기 오염",
        "Water Pollution": "수질 오염",
        "Soil Contamination": "토양 오염",
        "Particulate Matter": "미세먼지",
        "Greenhouse Gas": "온실가스",
        "Carbon Footprint": "탄소 발자국",
        "Carbon Neutrality": "탄소 중립",
        "Climate Change": "기후 변화",
        "Global Warming": "지구 온난화",
        "Renewable Energy": "재생 에너지",
        "Solar Energy": "태양 에너지",
        "Wind Energy": "풍력 에너지",
        "Geothermal Energy": "지열 에너지",
        "Biomass": "바이오매스",
        "Energy Efficiency": "에너지 효율",
        "Life Cycle Assessment": "생애 주기 평가",
        "Environmental Impact Assessment": "환경 영향 평가",
        "Wastewater Treatment": "폐수 처리",
        "Sewage": "하수",
        "Activated Sludge": "활성 슬러지",
        "Biological Oxygen Demand": "생물학적 산소 요구량",
        "Chemical Oxygen Demand": "화학적 산소 요구량",
        "Eutrophication": "부영양화",
        "Acid Rain": "산성비",
        "Ozone Depletion": "오존층 파괴",
        "Hazardous Waste": "유해 폐기물",
        "Recycling": "재활용",
        "Circular Economy": "순환 경제",
        "Bioremediation": "생물학적 정화",
        "Environmental Monitoring": "환경 모니터링",
        "Air Quality Index": "대기질 지수",
        "Drinking Water Standards": "음용수 기준",
        "Ecosystem": "생태계",
        "Biodiversity": "생물 다양성",
        "Sustainable Development Goals": "지속 가능 발전 목표",
        "Paris Agreement": "파리 협정",
        "Emission Standards": "배출 기준",
        "Carbon Capture": "탄소 포집",
        "Smart City": "스마트 시티",
        "Green Building": "친환경 건물",
        "Desertification": "사막화",
        "Deforestation": "삼림 벌채",
        "Environmental Law": "환경법",
    },

    "Biotechnology": {
        **_CHEMISTRY_BASE,
        **_BIO_MOLECULAR,
        "Cell Culture": "세포 배양",
        "PCR": "PCR(중합효소 연쇄 반응)",
        "Gene Expression": "유전자 발현",
        "Cloning": "클로닝",
        "Plasmid": "플라스미드",
        "Fermentation": "발효",
        "Bioreactor": "생물 반응기",
        "Stem Cell": "줄기세포",
        "CRISPR": "크리스퍼(유전자 편집 기술)",
        "Recombinant DNA": "재조합 DNA",
        "Electrophoresis": "전기영동",
        "Western Blot": "웨스턴 블롯",
        "Transcription": "전사",
        "Translation": "번역",
        "Codon": "코돈",
        "Gene Therapy": "유전자 치료",
        "Biosensor": "바이오센서",
        "Biomarker": "바이오마커",
        "Proteomics": "단백질체학",
        "Genomics": "유전체학",
        "Metabolomics": "대사체학",
        "Bioinformatics": "생물정보학",
        "Sequencing": "염기서열 분석",
        "Next-generation Sequencing": "차세대 염기서열 분석",
        "Flow Cytometry": "유세포 분석",
        "ELISA": "효소결합 면역흡착 분석법",
        "Mass Spectrometry": "질량 분석법",
        "Chromatography": "크로마토그래피",
        "Centrifugation": "원심분리",
        "Fluorescence": "형광",
        "Promoter": "프로모터",
        "Intron": "인트론",
        "Exon": "엑손",
        "Epigenetics": "후성유전학",
        "Methylation": "메틸화",
        "Mitosis": "유사분열",
        "Meiosis": "감수분열",
        "Apoptosis": "세포 사멸",
        "Cell Signaling": "세포 신호전달",
        "Receptor": "수용체",
        "Glycolysis": "해당작용",
        "Photosynthesis": "광합성",
        "Mitochondria": "미토콘드리아",
        "Ribosome": "리보솜",
        "Monoclonal Antibody": "단클론 항체",
        "Biopharmaceutical": "바이오의약품",
        "Tissue Engineering": "조직공학",
        "Microbiome": "마이크로바이옴",
        "Synthetic Biology": "합성생물학",
        "Protein Engineering": "단백질 공학",
        "Enzyme Kinetics": "효소 반응속도론",
        "Oncogene": "종양 유전자",
    },

    "Mathematics": {
        **_STATISTICS_BASE,
        "Calculus": "미적분학",
        "Differential Equation": "미분방정식",
        "Linear Algebra": "선형대수학",
        "Matrix": "행렬",
        "Eigenvalue": "고유값",
        "Eigenvector": "고유벡터",
        "Theorem": "정리",
        "Proof": "증명",
        "Integral": "적분",
        "Derivative": "도함수",
        "Limit": "극한",
        "Continuity": "연속성",
        "Convergence": "수렴",
        "Divergence": "발산",
        "Set Theory": "집합론",
        "Number Theory": "수론",
        "Topology": "위상수학",
        "Abstract Algebra": "추상대수학",
        "Real Analysis": "실해석학",
        "Complex Analysis": "복소해석학",
        "Numerical Analysis": "수치해석",
        "Discrete Mathematics": "이산수학",
        "Graph Theory": "그래프 이론",
        "Combinatorics": "조합론",
        "Permutation": "순열",
        "Combination": "조합",
        "Binomial Theorem": "이항정리",
        "Mathematical Induction": "수학적 귀납법",
        "Axiom": "공리",
        "Lemma": "보조 정리",
        "Conjecture": "추측",
        "Counterexample": "반례",
        "Function": "함수",
        "Domain": "정의역",
        "Range": "치역",
        "Bijection": "전단사 함수",
        "Inverse Function": "역함수",
        "Sequence": "수열",
        "Series": "급수",
        "Taylor Series": "테일러 급수",
        "Fourier Series": "푸리에 급수",
        "Vector Space": "벡터 공간",
        "Basis": "기저",
        "Dimension": "차원",
        "Linear Independence": "선형 독립",
        "Inner Product": "내적",
        "Determinant": "행렬식",
        "Inverse Matrix": "역행렬",
        "Partial Derivative": "편미분",
        "Gradient": "기울기",
        "Lagrange Multiplier": "라그랑주 승수",
        "Optimization": "최적화",
        "Group": "군",
        "Ring": "환",
        "Field": "체",
        "Isomorphism": "동형사상",
        "Metric Space": "거리 공간",
        "Compactness": "컴팩트성",
        "Measure Theory": "측도론",
        "Lebesgue Integral": "르베그 적분",
        "Markov Chain": "마르코프 연쇄",
    },

    "Physics": {
        **_PHYSICS_MECHANICS,
        **_THERMODYNAMICS,
        "Mechanics": "역학",
        "Electromagnetism": "전자기학",
        "Quantum Mechanics": "양자역학",
        "Relativity": "상대성 이론",
        "Wave": "파동",
        "Optics": "광학",
        "Nuclear Physics": "핵물리학",
        "Particle Physics": "입자물리학",
        "Photon": "광자",
        "Electron": "전자",
        "Gravity": "중력",
        "Conservation of Momentum": "운동량 보존 법칙",
        "Tension": "장력",
        "Centripetal Force": "구심력",
        "Angular Momentum": "각운동량",
        "Simple Harmonic Motion": "단순 조화 운동",
        "Hooke's Law": "훅의 법칙",
        "Buoyancy": "부력",
        "Archimedes' Principle": "아르키메데스의 원리",
        "Ideal Gas Law": "이상 기체 법칙",
        "Electric Charge": "전하",
        "Electric Field": "전기장",
        "Electric Potential": "전위",
        "Coulomb's Law": "쿨롱의 법칙",
        "Magnetic Field": "자기장",
        "Magnetic Force": "자기력",
        "Faraday's Law": "패러데이 법칙",
        "Electromagnetic Induction": "전자기 유도",
        "Maxwell's Equations": "맥스웰 방정식",
        "Speed of Light": "빛의 속도",
        "Refraction": "굴절",
        "Reflection": "반사",
        "Diffraction": "회절",
        "Interference": "간섭",
        "Wavelength": "파장",
        "Doppler Effect": "도플러 효과",
        "Wave-particle Duality": "파동-입자 이중성",
        "Uncertainty Principle": "불확정성 원리",
        "Schrödinger Equation": "슈뢰딩거 방정식",
        "Quantum Entanglement": "양자 얽힘",
        "Spin": "스핀",
        "Special Relativity": "특수 상대성 이론",
        "General Relativity": "일반 상대성 이론",
        "Black Hole": "블랙홀",
        "Dark Matter": "암흑 물질",
        "Big Bang": "빅뱅",
        "Nuclear Fission": "핵분열",
        "Nuclear Fusion": "핵융합",
        "Half-life": "반감기",
        "Standard Model": "표준 모형",
        "Quark": "쿼크",
        "Higgs Field": "힉스 장",
        "Superconductivity": "초전도성",
    },

    "Medical": {
        **_BIO_MOLECULAR,
        **_MEDICAL_BASIC,
        "Anatomy": "해부학",
        "Physiology": "생리학",
        "Pathology": "병리학",
        "Etiology": "병인론",
        "Cardiac": "심장의",
        "Pulmonary": "폐의",
        "Renal": "신장의",
        "Hepatic": "간의",
        "Neurological": "신경학적",
        "Biopsy": "생검",
        "MRI": "자기공명영상",
        "CT Scan": "컴퓨터 단층촬영",
        "Hypertension": "고혈압",
        "Diabetes Mellitus": "당뇨병",
        "Cardiovascular Disease": "심혈관 질환",
        "Myocardial Infarction": "심근경색",
        "Stroke": "뇌졸중",
        "Arrhythmia": "부정맥",
        "Heart Failure": "심부전",
        "Atherosclerosis": "동맥경화",
        "Thrombosis": "혈전증",
        "Pneumonia": "폐렴",
        "Tuberculosis": "결핵",
        "Asthma": "천식",
        "COPD": "만성 폐쇄성 폐질환",
        "Chronic Kidney Disease": "만성 신장 질환",
        "Liver Cirrhosis": "간경변",
        "Hepatitis": "간염",
        "Anemia": "빈혈",
        "Leukemia": "백혈병",
        "Lymphoma": "림프종",
        "Metastasis": "전이",
        "Tumor": "종양",
        "Benign": "양성",
        "Malignant": "악성",
        "Chemotherapy": "화학 요법",
        "Radiation Therapy": "방사선 치료",
        "Immunotherapy": "면역 치료",
        "Antiviral": "항바이러스제",
        "Prophylaxis": "예방",
        "Screening": "선별 검사",
        "ECG": "심전도",
        "Ultrasound": "초음파",
        "X-ray": "엑스레이",
        "Endoscopy": "내시경",
        "Intravenous": "정맥 내",
        "Subcutaneous": "피하",
        "Contraindication": "금기",
        "Autoimmune": "자가면역",
        "Rheumatoid Arthritis": "류마티스 관절염",
        "Osteoporosis": "골다공증",
        "Epilepsy": "뇌전증",
        "Parkinson's Disease": "파킨슨병",
        "Alzheimer's Disease": "알츠하이머병",
        "Dementia": "치매",
        "Depression": "우울증",
        "Schizophrenia": "조현병",
        "Sepsis": "패혈증",
        "Evidence-Based Medicine": "근거 중심 의학",
        "Telemedicine": "원격 의료",
        "Precision Medicine": "정밀 의학",
        "Biomarker": "생체 표지자",
        "Comorbidity": "동반 질환",
    },

    "Nursing": {
        **_MEDICAL_BASIC,
        "Assessment": "사정",
        "Planning": "계획",
        "Implementation": "수행",
        "Evaluation": "평가",
        "Intervention": "중재",
        "Outcome": "결과",
        "Respiration": "호흡",
        "Oxygen Saturation": "산소 포화도",
        "Medication": "투약",
        "Catheter": "카테터",
        "Wound Care": "상처 간호",
        "Infection Control": "감염 관리",
        "Aseptic Technique": "무균술",
        "Patient Safety": "환자 안전",
        "Documentation": "기록",
        "Ethics": "윤리",
        "Holistic Care": "전인 간호",
        "Evidence-Based Practice": "근거 중심 실무",
        "Nursing Process": "간호 과정",
        "Nursing Diagnosis": "간호 진단",
        "SOAP Note": "SOAP 기록",
        "Auscultation": "청진",
        "Percussion": "타진",
        "Palpation": "촉진",
        "Pain Scale": "통증 척도",
        "Glasgow Coma Scale": "글래스고 혼수 척도",
        "Fall Risk Assessment": "낙상 위험 사정",
        "Pressure Ulcer": "압박 궤양",
        "Braden Scale": "브레이든 척도",
        "Fluid Balance": "수액 균형",
        "Intake and Output": "섭취량 및 배설량",
        "Nasogastric Tube": "비위관",
        "Foley Catheter": "폴리 카테터",
        "Suctioning": "흡인",
        "Oxygen Therapy": "산소 요법",
        "Blood Glucose Monitoring": "혈당 모니터링",
        "Insulin Administration": "인슐린 투여",
        "Central Venous Line": "중심 정맥관",
        "Transfusion": "수혈",
        "Five Rights": "투약 5원칙",
        "Triage": "중증도 분류",
        "Emergency Care": "응급 간호",
        "CPR": "심폐소생술",
        "AED": "자동 제세동기",
        "Post-operative Care": "수술 후 간호",
        "Pre-operative Care": "수술 전 간호",
        "End-of-Life Care": "임종 간호",
        "Discharge Planning": "퇴원 계획",
        "Patient Education": "환자 교육",
        "Community Health": "지역사회 간호",
        "Maternal Nursing": "모성 간호",
        "Pediatric Nursing": "아동 간호",
        "Geriatric Nursing": "노인 간호",
        "Psychiatric Nursing": "정신 간호",
        "Therapeutic Communication": "치료적 의사소통",
        "Empathy": "공감",
        "Health Promotion": "건강 증진",
        "Standard Precaution": "표준 주의",
        "Hand Hygiene": "손 위생",
        "PPE": "개인 보호 장비",
        "Isolation": "격리",
        "Sterilization": "멸균",
        "Disinfection": "소독",
        "Nosocomial Infection": "병원 감염",
        "Quality Improvement": "질 향상",
    },

    "Pharmacy": {
        **_BIO_MOLECULAR,
        **_MEDICAL_BASIC,
        **_CHEMISTRY_BASE,
        "Pharmacokinetics": "약동학",
        "Pharmacodynamics": "약력학",
        "Absorption": "흡수",
        "Distribution": "분포",
        "Metabolism": "대사",
        "Excretion": "배설",
        "Bioavailability": "생체이용률",
        "Half-life": "반감기",
        "Steady-state Concentration": "정상 상태 농도",
        "Therapeutic Index": "치료 지수",
        "Drug Interaction": "약물 상호작용",
        "Adverse Drug Reaction": "약물 이상 반응",
        "Prescription": "처방",
        "Over-the-Counter": "일반 의약품",
        "Generic Drug": "제네릭 의약품",
        "Brand-name Drug": "오리지널 의약품",
        "Active Ingredient": "활성 성분",
        "Excipient": "부형제",
        "Formulation": "제형",
        "Tablet": "정제",
        "Capsule": "캡슐",
        "Suspension": "현탁제",
        "Solution": "용액",
        "Ointment": "연고",
        "Suppository": "좌제",
        "Controlled Release": "서방형 제제",
        "Drug Delivery System": "약물 전달 시스템",
        "Receptor Binding": "수용체 결합",
        "Agonist": "작용제",
        "Antagonist": "길항제",
        "Inhibitor": "억제제",
        "Cytochrome P450": "사이토크롬 P450 효소",
        "First-pass Effect": "초회 통과 효과",
        "Loading Dose": "부하 용량",
        "Maintenance Dose": "유지 용량",
        "Drug Approval": "의약품 승인",
        "Phase I Trial": "1상 임상시험",
        "Phase II Trial": "2상 임상시험",
        "Phase III Trial": "3상 임상시험",
        "Phase IV Trial": "4상 임상시험(시판 후 조사)",
        "Pharmacovigilance": "의약품 안전성 감시",
        "Drug Recall": "의약품 회수",
        "Good Manufacturing Practice": "우수 의약품 제조 기준",
        "Good Clinical Practice": "우수 임상 시험 기준",
        "Pharmacogenomics": "약물유전체학",
        "Personalized Medicine": "맞춤 의학",
        "Compounding": "조제",
        "Dispensing": "조제 및 투약",
        "Drug Counseling": "복약 상담",
        "Medication Therapy Management": "약물 치료 관리",
        "Antimicrobial Resistance": "항생제 내성",
        "Vaccine Development": "백신 개발",
        "Biologics": "바이오 의약품",
        "Narcotic": "마약류",
        "Controlled Substance": "향정신성 의약품",
        "Polypharmacy": "다약제 복용",
        "Drug Allergy": "약물 알레르기",
        "Therapeutic Drug Monitoring": "치료 약물 농도 모니터링",
        "Compendium": "약전",
    },

    "Architecture": {
        "Architecture": "건축학",
        "Structural Analysis": "구조 해석",
        "Blueprint": "설계 도면",
        "Load Bearing": "하중 지지",
        "Foundation": "기초",
        "Beam": "보",
        "Column": "기둥",
        "Facade": "파사드(건물 외벽)",
        "Urban Planning": "도시 계획",
        "Zoning": "용도 지역",
        "Sustainability": "지속 가능성",
        "Green Building": "친환경 건물",
        "HVAC": "냉난방 및 환기 시스템",
        "Acoustics": "음향학",
        "BIM": "건물 정보 모델링",
        "Construction": "시공",
        "Renovation": "리노베이션",
        "Interior": "실내",
        "Exterior": "외부",
        "Site Analysis": "대지 분석",
        "Floor Plan": "평면도",
        "Elevation": "입면도",
        "Section": "단면도",
        "Isometric Drawing": "등축 투영도",
        "Scale Model": "축척 모형",
        "Massing": "매싱(건물 덩어리)",
        "Rhythm": "리듬",
        "Axis": "축",
        "Circulation": "동선",
        "Spatial Sequence": "공간 시퀀스",
        "Fenestration": "창문 배치",
        "Skylight": "천창",
        "Cantilever": "캔틸레버",
        "Arch": "아치",
        "Vault": "볼트",
        "Dome": "돔",
        "Truss": "트러스",
        "Shear Wall": "전단벽",
        "Retaining Wall": "옹벽",
        "Curtain Wall": "커튼월",
        "Cladding": "외장재",
        "Insulation": "단열",
        "Waterproofing": "방수",
        "Concrete": "콘크리트",
        "Steel": "철골",
        "Timber": "목재",
        "Masonry": "조적",
        "Adaptive Reuse": "용도 전환",
        "Prefabrication": "조립식 공법",
        "Modular Design": "모듈 설계",
        "Parametric Design": "파라메트릭 설계",
        "LEED Certification": "LEED 인증",
        "Passive Design": "패시브 설계",
        "Daylighting": "자연 채광",
        "Modernism": "모더니즘",
        "Postmodernism": "포스트모더니즘",
        "Floor Area Ratio": "용적률",
        "Building Coverage Ratio": "건폐율",
        "Landscape Architecture": "조경",
        "Universal Design": "유니버설 디자인",
        "Accessibility": "접근성",
        "Building Code": "건축 법규",
        "Permit": "허가",
        "Passive House": "패시브 하우스",
        "Net Zero Building": "넷제로 건물",
        "Biophilic Design": "생물 친화적 설계",
    },

    # ─────────────────────────────────────────────────────────────────
    # 문과 (Humanities & Social Sciences)
    # ─────────────────────────────────────────────────────────────────

    "Business Administration": {
        **_BUSINESS_BASE,
        **_MARKETING_BASE,
        **_ACCOUNTING_BASE,
        "Strategic Planning": "전략 기획",
        "Outsourcing": "외주",
        "Entrepreneurship": "기업가 정신",
        "Venture Capital": "벤처 캐피털",
        "Budget": "예산",
        "Forecast": "예측",
        "Organizational Structure": "조직 구조",
        "Corporate Culture": "기업 문화",
        "Human Resource Management": "인적 자원 관리",
        "Recruitment": "채용",
        "Talent Management": "인재 관리",
        "Performance Appraisal": "성과 평가",
        "Compensation": "보상",
        "Employee Engagement": "직원 몰입도",
        "Leadership": "리더십",
        "Delegation": "위임",
        "Empowerment": "권한 부여",
        "Change Management": "변화 관리",
        "Porter's Five Forces": "포터의 5가지 경쟁 요인",
        "Blue Ocean Strategy": "블루오션 전략",
        "Core Competency": "핵심 역량",
        "Diversification": "다각화",
        "Vertical Integration": "수직적 통합",
        "Horizontal Integration": "수평적 통합",
        "Joint Venture": "합작 투자",
        "Strategic Alliance": "전략적 제휴",
        "Franchise": "프랜차이즈",
        "Intellectual Property": "지적 재산",
        "ERP": "전사적 자원 관리",
        "Business Intelligence": "비즈니스 인텔리전스",
        "Operations Management": "운영 관리",
        "Project Management": "프로젝트 관리",
        "Corporate Social Responsibility": "기업의 사회적 책임",
        "ESG": "ESG(환경·사회·지배구조)",
        "Economies of Scale": "규모의 경제",
        "Break-even Point": "손익분기점",
        "Fixed Cost": "고정 비용",
        "Variable Cost": "변동 비용",
        "OKR": "OKR(목표 및 핵심 결과)",
        "Lean Startup": "린 스타트업",
        "Minimum Viable Product": "최소 기능 제품",
        "Pivot": "피벗",
        "IPO": "기업 공개",
        "Due Diligence": "실사",
        "Negotiation": "협상",
        "Conflict Management": "갈등 관리",
    },

    "Economics": {
        **_STATISTICS_BASE,
        **_BUSINESS_BASE,
        "Economics": "경제학",
        "Supply": "공급",
        "Demand": "수요",
        "Elasticity": "탄력성",
        "Inflation": "인플레이션",
        "Deflation": "디플레이션",
        "GDP": "국내총생산",
        "GNP": "국민총생산",
        "Unemployment": "실업",
        "Fiscal Policy": "재정 정책",
        "Monetary Policy": "통화 정책",
        "Interest Rate": "금리",
        "Exchange Rate": "환율",
        "Trade Balance": "무역 수지",
        "Tariff": "관세",
        "Subsidy": "보조금",
        "Monopoly": "독점",
        "Oligopoly": "과점",
        "Perfect Competition": "완전 경쟁",
        "Market Failure": "시장 실패",
        "Externality": "외부 효과",
        "Public Good": "공공재",
        "Opportunity Cost": "기회 비용",
        "Marginal Cost": "한계 비용",
        "Consumer Surplus": "소비자 잉여",
        "Producer Surplus": "생산자 잉여",
        "Comparative Advantage": "비교 우위",
        "Absolute Advantage": "절대 우위",
        "Balance of Payments": "국제 수지",
        "Foreign Direct Investment": "외국인 직접 투자",
        "Purchasing Power Parity": "구매력 평가",
        "Money Supply": "통화량",
        "Quantitative Easing": "양적 완화",
        "Central Bank": "중앙은행",
        "Bond": "채권",
        "Financial Crisis": "금융 위기",
        "Recession": "경기 침체",
        "Business Cycle": "경기 순환",
        "Consumer Price Index": "소비자 물가 지수",
        "Gini Coefficient": "지니 계수",
        "Microeconomics": "미시경제학",
        "Macroeconomics": "거시경제학",
        "Behavioral Economics": "행동경제학",
        "Game Theory": "게임 이론",
        "Nash Equilibrium": "내시 균형",
        "Prisoner's Dilemma": "죄수의 딜레마",
        "Moral Hazard": "도덕적 해이",
        "Adverse Selection": "역선택",
        "Keynesian Economics": "케인즈 경제학",
        "Aggregate Demand": "총수요",
        "Aggregate Supply": "총공급",
        "Multiplier Effect": "승수 효과",
        "Stagflation": "스태그플레이션",
        "World Trade Organization": "세계 무역 기구",
        "International Monetary Fund": "국제 통화 기금",
        "Cryptocurrency": "암호 화폐",
        "Sharing Economy": "공유 경제",
        "Labor Market": "노동 시장",
        "Minimum Wage": "최저 임금",
    },

    "Finance": {
        **_STATISTICS_BASE,
        **_ACCOUNTING_BASE,
        **_BUSINESS_BASE,
        "Finance": "재무학",
        "Capital Market": "자본 시장",
        "Money Market": "단기 금융 시장",
        "Stock": "주식",
        "Bond": "채권",
        "Derivatives": "파생 상품",
        "Futures": "선물",
        "Options": "옵션",
        "Swap": "스왑",
        "Hedge Fund": "헤지 펀드",
        "Mutual Fund": "뮤추얼 펀드",
        "ETF": "상장지수펀드",
        "Portfolio": "포트폴리오",
        "Asset Allocation": "자산 배분",
        "Diversification": "분산 투자",
        "Risk-Return Tradeoff": "위험-수익 상충 관계",
        "Beta": "베타",
        "Alpha": "알파",
        "Sharpe Ratio": "샤프 비율",
        "Capital Asset Pricing Model": "자본자산 가격결정 모형",
        "Efficient Market Hypothesis": "효율적 시장 가설",
        "Time Value of Money": "화폐의 시간 가치",
        "Present Value": "현재 가치",
        "Future Value": "미래 가치",
        "Net Present Value": "순현재가치",
        "Internal Rate of Return": "내부 수익률",
        "Discount Rate": "할인율",
        "Yield to Maturity": "만기 수익률",
        "Credit Risk": "신용 위험",
        "Market Risk": "시장 위험",
        "Liquidity Risk": "유동성 위험",
        "Systemic Risk": "시스템 위험",
        "Volatility": "변동성",
        "Value at Risk": "기대 손실",
        "Stress Test": "스트레스 테스트",
        "Basel III": "바젤 III(국제 은행 자본 규제)",
        "Capital Adequacy Ratio": "자기자본비율",
        "Leverage": "레버리지",
        "Short Selling": "공매도",
        "Arbitrage": "차익 거래",
        "Investment Banking": "투자 은행",
        "Commercial Banking": "상업 은행",
        "Private Equity": "사모 펀드",
        "Venture Capital": "벤처 캐피털",
        "IPO": "기업 공개",
        "Dividend": "배당금",
        "Stock Split": "주식 분할",
        "Bull Market": "강세장",
        "Bear Market": "약세장",
        "Technical Analysis": "기술적 분석",
        "Fundamental Analysis": "기본적 분석",
        "Credit Rating": "신용 등급",
        "FinTech": "핀테크",
        "Digital Banking": "디지털 뱅킹",
        "Cryptocurrency": "암호 화폐",
        "Blockchain": "블록체인",
        "DeFi": "탈중앙화 금융",
        "Behavioral Finance": "행동 재무학",
        "Corporate Finance": "기업 재무",
    },

    "Marketing": {
        **_BUSINESS_BASE,
        **_MARKETING_BASE,
        "Product": "제품",
        "Price": "가격",
        "Place": "유통",
        "Promotion": "촉진",
        "Digital Marketing": "디지털 마케팅",
        "Social Media": "소셜 미디어",
        "Content Marketing": "콘텐츠 마케팅",
        "SEO": "검색 엔진 최적화",
        "Customer Loyalty": "고객 충성도",
        "Customer Retention": "고객 유지",
        "Sales Funnel": "판매 깔때기",
        "Lead Generation": "리드 생성",
        "Value Proposition": "가치 제안",
        "AIDA Model": "AIDA 모델(주의-관심-욕구-행동)",
        "Market Research": "시장 조사",
        "Buyer Persona": "구매자 페르소나",
        "Customer Journey": "고객 여정",
        "Touchpoint": "접점",
        "Omnichannel": "옴니채널",
        "Churn Rate": "이탈률",
        "Net Promoter Score": "순 추천 지수",
        "Brand Image": "브랜드 이미지",
        "Brand Loyalty": "브랜드 충성도",
        "Rebranding": "리브랜딩",
        "Product Lifecycle": "제품 수명 주기",
        "New Product Development": "신제품 개발",
        "Product Differentiation": "제품 차별화",
        "Competitive Analysis": "경쟁사 분석",
        "PEST Analysis": "PEST 분석",
        "Pricing Strategy": "가격 전략",
        "Penetration Pricing": "침투 가격",
        "Skimming Pricing": "스키밍 가격",
        "Dynamic Pricing": "동적 가격",
        "Freemium": "프리미엄 모델",
        "Subscription Model": "구독 모델",
        "Distribution Channel": "유통 채널",
        "E-commerce": "전자상거래",
        "Public Relations": "홍보",
        "Influencer Marketing": "인플루언서 마케팅",
        "Affiliate Marketing": "제휴 마케팅",
        "Email Marketing": "이메일 마케팅",
        "A/B Testing": "A/B 테스트",
        "Click-through Rate": "클릭률",
        "Engagement Rate": "참여율",
        "Viral Marketing": "바이럴 마케팅",
        "Word of Mouth": "구전 마케팅",
        "Experiential Marketing": "체험 마케팅",
        "Neuromarketing": "뉴로마케팅",
        "Data-Driven Marketing": "데이터 기반 마케팅",
        "Marketing Automation": "마케팅 자동화",
        "Demographics": "인구 통계",
        "Focus Group": "포커스 그룹",
        "Cross-selling": "교차 판매",
        "Up-selling": "상향 판매",
        "Sponsorship": "스폰서십",
    },

    "Accounting": {
        **_ACCOUNTING_BASE,
        **_BUSINESS_BASE,
        "Debit": "차변",
        "Credit": "대변",
        "Journal Entry": "분개",
        "Ledger": "원장",
        "Trial Balance": "시산표",
        "Amortization": "상각",
        "GAAP": "일반회계기준",
        "IFRS": "국제회계기준",
        "Accrual": "발생주의",
        "Inventory": "재고",
        "Accounts Receivable": "매출채권",
        "Accounts Payable": "매입채무",
        "Payroll": "급여",
        "Cost Accounting": "원가회계",
        "Current Asset": "유동 자산",
        "Non-current Asset": "비유동 자산",
        "Retained Earnings": "이익 잉여금",
        "Paid-in Capital": "납입 자본금",
        "Treasury Stock": "자기 주식",
        "Dividend": "배당금",
        "Earnings Per Share": "주당 순이익",
        "Price-to-Earnings Ratio": "주가수익비율",
        "Book Value": "장부 가액",
        "Fair Value": "공정 가치",
        "Impairment": "손상차손",
        "Goodwill": "영업권",
        "Intangible Asset": "무형 자산",
        "Tangible Asset": "유형 자산",
        "Capital Expenditure": "자본적 지출",
        "Operating Income": "영업 이익",
        "Liquidity": "유동성",
        "Solvency": "지급 능력",
        "Current Ratio": "유동 비율",
        "Quick Ratio": "당좌 비율",
        "Debt-to-Equity Ratio": "부채비율",
        "Return on Equity": "자기자본이익률",
        "Return on Assets": "자산수익률",
        "Asset Turnover": "자산 회전율",
        "Inventory Turnover": "재고 회전율",
        "Variance Analysis": "차이 분석",
        "Standard Cost": "표준 원가",
        "Activity-Based Costing": "활동 기준 원가 계산",
        "Transfer Pricing": "이전 가격",
        "Consolidation": "연결 재무제표",
        "Revenue Recognition": "수익 인식",
        "Matching Principle": "대응 원칙",
        "Going Concern": "계속 기업 가정",
        "Internal Control": "내부 통제",
        "Deferred Tax": "이연 법인세",
        "Value Added Tax": "부가가치세",
        "Corporate Tax": "법인세",
        "Double-entry Bookkeeping": "복식 부기",
        "Chart of Accounts": "계정 과목표",
        "Reconciliation": "조정",
        "Management Accounting": "관리 회계",
        "Financial Accounting": "재무 회계",
    },

    "Law": {
        "Law": "법학",
        "Constitution": "헌법",
        "Statute": "법률",
        "Regulation": "규정",
        "Ordinance": "조례",
        "Civil Law": "민법",
        "Criminal Law": "형법",
        "Commercial Law": "상법",
        "Administrative Law": "행정법",
        "Procedural Law": "절차법",
        "Substantive Law": "실체법",
        "Public Law": "공법",
        "Private Law": "사법",
        "International Law": "국제법",
        "Common Law": "보통법",
        "Civil Code": "민법전",
        "Penal Code": "형법전",
        "Tort": "불법행위",
        "Negligence": "과실",
        "Strict Liability": "무과실 책임",
        "Vicarious Liability": "사용자 책임",
        "Contract": "계약",
        "Offer": "청약",
        "Acceptance": "승낙",
        "Consideration": "약인",
        "Breach of Contract": "계약 위반",
        "Specific Performance": "특정 이행",
        "Damages": "손해 배상",
        "Property Right": "재산권",
        "Real Property": "부동산",
        "Personal Property": "동산",
        "Easement": "지역권",
        "Mortgage": "저당권",
        "Lease": "임대차",
        "Inheritance": "상속",
        "Trust": "신탁",
        "Family Law": "가족법",
        "Divorce": "이혼",
        "Custody": "양육권",
        "Adoption": "입양",
        "Crime": "범죄",
        "Misdemeanor": "경범죄",
        "Felony": "중범죄",
        "Mens Rea": "범죄 고의",
        "Actus Reus": "범죄 행위",
        "Defense": "변호",
        "Self-defense": "정당방위",
        "Burden of Proof": "입증 책임",
        "Beyond Reasonable Doubt": "합리적 의심을 넘어",
        "Preponderance of Evidence": "증거 우월",
        "Plaintiff": "원고",
        "Defendant": "피고",
        "Prosecutor": "검사",
        "Attorney": "변호사",
        "Judge": "판사",
        "Jury": "배심원",
        "Witness": "증인",
        "Testimony": "증언",
        "Evidence": "증거",
        "Subpoena": "소환장",
        "Indictment": "기소장",
        "Trial": "재판",
        "Verdict": "평결",
        "Sentence": "선고",
        "Appeal": "항소",
        "Precedent": "판례",
        "Jurisdiction": "관할권",
        "Statute of Limitations": "공소 시효",
        "Due Process": "적법 절차",
        "Equal Protection": "평등 보호",
        "Fundamental Rights": "기본권",
        "Habeas Corpus": "인신보호영장",
        "Plea Bargain": "유죄 협상",
        "Mediation": "조정",
        "Arbitration": "중재",
        "Litigation": "소송",
        "Class Action": "집단 소송",
        "Bar Examination": "변호사 시험",
        "Legal Ethics": "법조 윤리",
    },

    "Education": {
        "Education": "교육학",
        "Pedagogy": "교수법",
        "Curriculum": "교육과정",
        "Syllabus": "강의계획서",
        "Lesson Plan": "수업 지도안",
        "Learning Outcome": "학습 성과",
        "Learning Objective": "학습 목표",
        "Bloom's Taxonomy": "블룸의 분류",
        "Cognitive Domain": "인지적 영역",
        "Affective Domain": "정의적 영역",
        "Psychomotor Domain": "심동적 영역",
        "Instructional Design": "교수 설계",
        "ADDIE Model": "ADDIE 모형",
        "Backward Design": "백워드 설계",
        "Differentiated Instruction": "차별화 수업",
        "Active Learning": "능동 학습",
        "Flipped Classroom": "플립 러닝",
        "Blended Learning": "혼합 학습",
        "Project-Based Learning": "프로젝트 기반 학습",
        "Problem-Based Learning": "문제 기반 학습",
        "Inquiry-Based Learning": "탐구 기반 학습",
        "Cooperative Learning": "협동 학습",
        "Constructivism": "구성주의",
        "Behaviorism": "행동주의",
        "Cognitivism": "인지주의",
        "Connectivism": "연결주의",
        "Zone of Proximal Development": "근접 발달 영역",
        "Scaffolding": "비계 설정",
        "Multiple Intelligences": "다중 지능",
        "Formative Assessment": "형성 평가",
        "Summative Assessment": "총괄 평가",
        "Diagnostic Assessment": "진단 평가",
        "Rubric": "루브릭",
        "Portfolio Assessment": "포트폴리오 평가",
        "Standardized Test": "표준화 시험",
        "Validity": "타당도",
        "Reliability": "신뢰도",
        "Norm-referenced Test": "규준 참조 평가",
        "Criterion-referenced Test": "준거 참조 평가",
        "Educational Psychology": "교육 심리학",
        "Developmental Psychology": "발달 심리학",
        "Special Education": "특수 교육",
        "Inclusive Education": "통합 교육",
        "Gifted Education": "영재 교육",
        "Early Childhood Education": "유아 교육",
        "Primary Education": "초등 교육",
        "Secondary Education": "중등 교육",
        "Higher Education": "고등 교육",
        "Adult Education": "성인 교육",
        "Lifelong Learning": "평생 학습",
        "Vocational Education": "직업 교육",
        "STEM Education": "STEM 교육",
        "Multicultural Education": "다문화 교육",
        "Educational Technology": "교육 공학",
        "Learning Management System": "학습 관리 시스템",
        "MOOC": "온라인 공개 강좌",
        "E-learning": "이러닝",
        "Digital Literacy": "디지털 리터러시",
        "Classroom Management": "학급 경영",
        "Student Engagement": "학생 참여",
        "Motivation": "동기",
        "Intrinsic Motivation": "내적 동기",
        "Extrinsic Motivation": "외적 동기",
        "Self-efficacy": "자기효능감",
        "Growth Mindset": "성장 마인드셋",
        "Metacognition": "메타인지",
        "Educational Policy": "교육 정책",
        "Teacher Training": "교사 교육",
        "Action Research": "실행 연구",
        "Reflective Practice": "성찰적 실천",
    },

    "Psychology": {
        "Psychology": "심리학",
        "Cognition": "인지",
        "Behavior": "행동",
        "Emotion": "감정",
        "Motivation": "동기",
        "Perception": "지각",
        "Memory": "기억",
        "Attention": "주의",
        "Learning": "학습",
        "Conditioning": "조건화",
        "Reinforcement": "강화",
        "Punishment": "처벌",
        "Classical Conditioning": "고전적 조건화",
        "Operant Conditioning": "조작적 조건화",
        "Cognitive Dissonance": "인지 부조화",
        "Self-efficacy": "자기효능감",
        "Personality": "성격",
        "Trait": "특성",
        "Disorder": "장애",
        "Therapy": "치료",
        "Psychotherapy": "심리치료",
        "Cognitive Behavioral Therapy": "인지행동치료",
        "Unconscious": "무의식",
        "Stress": "스트레스",
        "Coping": "대처",
        "Resilience": "회복탄력성",
        "Developmental Psychology": "발달 심리학",
        "Social Psychology": "사회 심리학",
        "Clinical Psychology": "임상 심리학",
        "Neuropsychology": "신경심리학",
        "Positive Psychology": "긍정 심리학",
        "Psychoanalysis": "정신분석",
        "Id": "이드",
        "Ego": "자아",
        "Superego": "초자아",
        "Defense Mechanism": "방어 기제",
        "Repression": "억압",
        "Projection": "투사",
        "Rationalization": "합리화",
        "Schema": "스키마",
        "Heuristic": "휴리스틱",
        "Cognitive Bias": "인지 편향",
        "Confirmation Bias": "확증 편향",
        "Attribution Theory": "귀인 이론",
        "Groupthink": "집단 사고",
        "Conformity": "동조",
        "Obedience": "복종",
        "Attitude": "태도",
        "Persuasion": "설득",
        "Stereotyping": "고정 관념",
        "Prejudice": "편견",
        "Discrimination": "차별",
        "Empathy": "공감",
        "Altruism": "이타주의",
        "Aggression": "공격성",
        "Attachment": "애착",
        "Short-term Memory": "단기 기억",
        "Long-term Memory": "장기 기억",
        "Working Memory": "작동 기억",
        "Encoding": "부호화",
        "Retrieval": "인출",
        "Forgetting": "망각",
        "Intelligence": "지능",
        "IQ": "지능 지수",
        "Multiple Intelligences": "다중 지능",
        "Emotional Intelligence": "감성 지능",
        "Consciousness": "의식",
        "Mindfulness": "마음챙김",
        "Maslow's Hierarchy": "매슬로의 욕구 계층",
        "Self-actualization": "자아실현",
        "Flow State": "플로 상태",
        "Growth Mindset": "성장 마인드셋",
        "Synapse": "시냅스",
        "Neurotransmitter": "신경전달물질",
        "Amygdala": "편도체",
        "Prefrontal Cortex": "전전두 피질",
    },

    "International Relations": {
        **_POLITICS_SOCIETY,
        "Diplomacy": "외교",
        "Multilateralism": "다자주의",
        "Bilateral": "양자 간",
        "Geopolitics": "지정학",
        "Sanctions": "제재",
        "Treaty": "조약",
        "Alliance": "동맹",
        "Deterrence": "억지력",
        "Soft Power": "소프트 파워",
        "Hard Power": "하드 파워",
        "Non-governmental Organization": "비정부 기구",
        "International Law": "국제법",
        "United Nations": "유엔",
        "Security Council": "안전보장이사회",
        "Refugee": "난민",
        "Conflict Resolution": "분쟁 해결",
        "Realism": "현실주의",
        "Constructivism": "구성주의",
        "Balance of Power": "세력 균형",
        "Security Dilemma": "안보 딜레마",
        "Nuclear Deterrence": "핵 억지",
        "Arms Control": "군비 통제",
        "Non-proliferation": "비확산",
        "Collective Security": "집단 안보",
        "Peacekeeping": "평화 유지",
        "Humanitarian Intervention": "인도주의적 개입",
        "International Trade": "국제 무역",
        "Free Trade": "자유 무역",
        "Protectionism": "보호주의",
        "Economic Sanctions": "경제 제재",
        "National Interest": "국가 이익",
        "Regional Integration": "지역 통합",
        "European Union": "유럽 연합",
        "ASEAN": "동남아시아 국가 연합",
        "NATO": "북대서양 조약 기구",
        "Colonialism": "식민주의",
        "Imperialism": "제국주의",
        "Cold War": "냉전",
        "Bipolar System": "양극 체제",
        "Multipolar System": "다극 체제",
        "Proxy War": "대리전",
        "Terrorism": "테러리즘",
        "Asymmetric Warfare": "비대칭 전쟁",
        "Cyber Warfare": "사이버 전쟁",
        "Paris Agreement": "파리 협정",
        "Sustainable Development Goals": "지속 가능 발전 목표",
        "Global Governance": "글로벌 거버넌스",
        "Migration": "이주",
        "Cultural Diplomacy": "문화 외교",
        "Public Diplomacy": "공공 외교",
        "Mediation": "조정",
        "International Court of Justice": "국제사법재판소",
        "Genocide": "집단학살",
        "War Crimes": "전쟁 범죄",
        "Self-determination": "자결권",
        "Democratization": "민주화",
        "Embargo": "금수 조치",
    },

    "Sociology": {
        **_POLITICS_SOCIETY,
        **_RESEARCH_BASE,
        "Sociology": "사회학",
        "Social Structure": "사회 구조",
        "Social Class": "사회 계층",
        "Inequality": "불평등",
        "Norms": "규범",
        "Values": "가치",
        "Culture": "문화",
        "Socialization": "사회화",
        "Institution": "제도",
        "Deviance": "일탈",
        "Social Mobility": "사회 이동",
        "Ethnicity": "민족성",
        "Gender": "젠더",
        "Power": "권력",
        "Community": "공동체",
        "Urbanization": "도시화",
        "Social Theory": "사회 이론",
        "Functionalism": "기능주의",
        "Conflict Theory": "갈등 이론",
        "Symbolic Interactionism": "상징적 상호작용론",
        "Postmodernism": "포스트모더니즘",
        "Feminism": "페미니즘",
        "Race": "인종",
        "Intersectionality": "교차성",
        "Social Capital": "사회 자본",
        "Cultural Capital": "문화 자본",
        "Habitus": "아비투스",
        "Discourse": "담론",
        "Social Construction": "사회적 구성",
        "Agency": "행위 능력",
        "Structure": "구조",
        "Ethnography": "민족지학",
        "Participant Observation": "참여 관찰",
        "Social Network": "사회 연결망",
        "Anomie": "아노미",
        "Social Control": "사회 통제",
        "Labeling Theory": "낙인 이론",
        "Stigma": "스티그마",
        "Social Movement": "사회 운동",
        "Collective Action": "집합 행동",
        "Social Stratification": "사회 계층화",
        "Meritocracy": "능력주의",
        "Poverty": "빈곤",
        "Welfare State": "복지 국가",
        "Family": "가족",
        "Marriage": "결혼",
        "Patriarchy": "가부장제",
        "Religion": "종교",
        "Secularization": "세속화",
        "Modernization": "근대화",
        "Industrialization": "산업화",
        "Information Society": "정보 사회",
        "Risk Society": "위험 사회",
        "Aging Society": "고령화 사회",
        "Diaspora": "디아스포라",
        "Social Exclusion": "사회적 배제",
        "Social Identity": "사회적 정체성",
    },

    "Social Welfare": {
        **_RESEARCH_BASE,
        "Social Welfare": "사회복지",
        "Social Work": "사회사업",
        "Welfare State": "복지 국가",
        "Social Security": "사회보장",
        "Social Insurance": "사회보험",
        "Public Assistance": "공공부조",
        "Social Service": "사회서비스",
        "Basic Income": "기본소득",
        "Universal Healthcare": "전 국민 건강보장",
        "Pension": "연금",
        "Unemployment Insurance": "실업보험",
        "Workers' Compensation": "산재보험",
        "Long-term Care Insurance": "장기요양보험",
        "Medicaid": "메디케이드",
        "Means Test": "자산 조사",
        "Eligibility": "수급 자격",
        "Beneficiary": "수급자",
        "Case Management": "사례 관리",
        "Intervention": "개입",
        "Strengths Perspective": "강점 관점",
        "Empowerment": "역량 강화",
        "Advocacy": "권익 옹호",
        "Person-in-Environment": "환경 속의 인간",
        "Ecological Perspective": "생태학적 관점",
        "Systems Theory": "체계 이론",
        "Family Therapy": "가족 치료",
        "Group Work": "집단 사회사업",
        "Community Organization": "지역사회 조직",
        "Community Development": "지역사회 개발",
        "Child Welfare": "아동 복지",
        "Child Protection": "아동 보호",
        "Foster Care": "위탁 보호",
        "Adoption": "입양",
        "Domestic Violence": "가정 폭력",
        "Elder Abuse": "노인 학대",
        "Geriatric Social Work": "노인 사회사업",
        "Disability Welfare": "장애인 복지",
        "Mental Health": "정신 건강",
        "Substance Abuse": "약물 남용",
        "Addiction": "중독",
        "Homelessness": "노숙",
        "Poverty Line": "빈곤선",
        "Income Inequality": "소득 불평등",
        "Social Exclusion": "사회적 배제",
        "Marginalization": "주변화",
        "Vulnerable Population": "취약 계층",
        "Multicultural Family": "다문화 가족",
        "Social Welfare Policy": "사회복지 정책",
        "Code of Ethics": "윤리 강령",
        "Confidentiality": "비밀 보장",
        "Self-determination": "자기결정권",
        "NGO": "비정부 기구",
        "Volunteerism": "자원봉사",
        "Crisis Intervention": "위기 개입",
        "Suicide Prevention": "자살 예방",
        "Trauma-informed Care": "트라우마 인식 기반 돌봄",
        "Resilience": "회복탄력성",
        "Quality of Life": "삶의 질",
        "Social Justice": "사회 정의",
        "Human Rights": "인권",
    },

    "Linguistics": {
        "Linguistics": "언어학",
        "Phonetics": "음성학",
        "Phonology": "음운론",
        "Morphology": "형태론",
        "Syntax": "통사론",
        "Semantics": "의미론",
        "Pragmatics": "화용론",
        "Sociolinguistics": "사회언어학",
        "Psycholinguistics": "심리언어학",
        "Historical Linguistics": "역사언어학",
        "Comparative Linguistics": "비교언어학",
        "Applied Linguistics": "응용언어학",
        "Computational Linguistics": "전산언어학",
        "Cognitive Linguistics": "인지언어학",
        "Phoneme": "음소",
        "Allophone": "이음",
        "Morpheme": "형태소",
        "Lexeme": "어휘소",
        "Word Formation": "단어 형성",
        "Inflection": "굴절",
        "Derivation": "파생",
        "Compound": "합성어",
        "Part of Speech": "품사",
        "Noun": "명사",
        "Verb": "동사",
        "Adjective": "형용사",
        "Adverb": "부사",
        "Tense": "시제",
        "Aspect": "상",
        "Mood": "법",
        "Voice": "태",
        "Sentence Structure": "문장 구조",
        "Subject": "주어",
        "Predicate": "술어",
        "Object": "목적어",
        "Modifier": "수식어",
        "Clause": "절",
        "Phrase": "구",
        "Dependency Grammar": "의존 문법",
        "Generative Grammar": "생성 문법",
        "Universal Grammar": "보편 문법",
        "Language Acquisition": "언어 습득",
        "First Language": "모국어",
        "Second Language": "제2언어",
        "Bilingualism": "이중언어 사용",
        "Multilingualism": "다중언어 사용",
        "Code-switching": "부호 전환",
        "Dialect": "방언",
        "Standard Language": "표준어",
        "Language Variation": "언어 변이",
        "Language Change": "언어 변화",
        "Etymology": "어원학",
        "Lexicon": "어휘부",
        "Corpus Linguistics": "말뭉치 언어학",
        "Discourse Analysis": "담화 분석",
        "Conversation Analysis": "대화 분석",
        "Speech Act": "화행",
        "Implicature": "함축",
        "Presupposition": "전제",
        "Anaphora": "대용어",
        "Metaphor": "은유",
        "Metonymy": "환유",
        "Sign Language": "수어",
        "Language Family": "어족",
        "Indo-European": "인도유럽어족",
        "Pidgin": "피진",
        "Creole": "크리올",
        "Endangered Language": "위기 언어",
    },

    "English Language & Literature": {
        "English Language": "영어학",
        "English Literature": "영문학",
        "Literary Criticism": "문학 비평",
        "Literary Theory": "문학 이론",
        "Literary Genre": "문학 장르",
        "Novel": "소설",
        "Short Story": "단편 소설",
        "Poetry": "시",
        "Drama": "드라마",
        "Tragedy": "비극",
        "Comedy": "희극",
        "Essay": "수필",
        "Fiction": "픽션",
        "Non-fiction": "논픽션",
        "Narrator": "화자",
        "Point of View": "시점",
        "First-person Narration": "1인칭 시점",
        "Third-person Narration": "3인칭 시점",
        "Omniscient Narrator": "전지적 시점",
        "Protagonist": "주인공",
        "Antagonist": "악역",
        "Character": "등장인물",
        "Plot": "줄거리",
        "Theme": "주제",
        "Setting": "배경",
        "Tone": "어조",
        "Mood": "분위기",
        "Symbol": "상징",
        "Allegory": "알레고리",
        "Irony": "아이러니",
        "Foreshadowing": "복선",
        "Flashback": "회상",
        "Climax": "절정",
        "Resolution": "결말",
        "Conflict": "갈등",
        "Metaphor": "은유",
        "Simile": "직유",
        "Personification": "의인법",
        "Hyperbole": "과장법",
        "Alliteration": "두운법",
        "Imagery": "심상",
        "Diction": "어조 선택",
        "Syntax": "통사",
        "Style": "문체",
        "Rhetoric": "수사학",
        "Sonnet": "소네트",
        "Iambic Pentameter": "약강 5보격",
        "Stanza": "연",
        "Verse": "운문",
        "Prose": "산문",
        "Free Verse": "자유시",
        "Rhyme Scheme": "운율 배치",
        "Old English": "고대 영어",
        "Middle English": "중세 영어",
        "Modern English": "근대 영어",
        "Renaissance Literature": "르네상스 문학",
        "Victorian Literature": "빅토리아 시대 문학",
        "Romanticism": "낭만주의",
        "Realism": "사실주의",
        "Modernism": "모더니즘",
        "Postmodernism": "포스트모더니즘",
        "Naturalism": "자연주의",
        "Shakespeare Studies": "셰익스피어 연구",
        "Comparative Literature": "비교 문학",
        "World Literature": "세계 문학",
        "Postcolonial Literature": "탈식민지 문학",
        "Feminist Criticism": "페미니즘 비평",
        "Marxist Criticism": "마르크스주의 비평",
        "New Criticism": "신비평",
        "Structuralism": "구조주의",
        "Deconstruction": "해체주의",
        "Reader-response Theory": "독자 반응 이론",
        "Translation Studies": "번역학",
        "TESOL": "외국어로서의 영어 교육",
        "TEFL": "외국어 영어 교수법",
        "Grammar": "문법",
        "Vocabulary": "어휘",
        "Academic Writing": "학술적 글쓰기",
        "Creative Writing": "창의적 글쓰기",
        "Discourse Analysis": "담화 분석",
        "Cultural Studies": "문화 연구",
        "Bibliography": "참고문헌",
        "Annotation": "주석",
        "Close Reading": "정독",
        "Allusion": "암시",
        "Motif": "모티프",
        "Archetype": "원형",
    },

    "Philosophy": {
        "Philosophy": "철학",
        "Metaphysics": "형이상학",
        "Epistemology": "인식론",
        "Ethics": "윤리학",
        "Logic": "논리학",
        "Aesthetics": "미학",
        "Ontology": "존재론",
        "Phenomenology": "현상학",
        "Existentialism": "실존주의",
        "Rationalism": "합리주의",
        "Empiricism": "경험주의",
        "Idealism": "관념론",
        "Materialism": "유물론",
        "Realism": "실재론",
        "Nominalism": "유명론",
        "Pragmatism": "실용주의",
        "Stoicism": "스토아주의",
        "Utilitarianism": "공리주의",
        "Deontology": "의무론",
        "Virtue Ethics": "덕 윤리",
        "Consequentialism": "결과주의",
        "Moral Relativism": "도덕 상대주의",
        "Moral Realism": "도덕 실재론",
        "Free Will": "자유 의지",
        "Determinism": "결정론",
        "Compatibilism": "양립가능론",
        "Mind-Body Problem": "심신 문제",
        "Dualism": "이원론",
        "Monism": "일원론",
        "Consciousness": "의식",
        "Qualia": "감각질",
        "Personal Identity": "개인 동일성",
        "Justified True Belief": "정당화된 참인 믿음",
        "Skepticism": "회의주의",
        "A Priori": "선험적",
        "A Posteriori": "후험적",
        "Analytic": "분석적",
        "Synthetic": "종합적",
        "Necessary Truth": "필연적 진리",
        "Contingent Truth": "우연적 진리",
        "Deductive Reasoning": "연역적 추론",
        "Inductive Reasoning": "귀납적 추론",
        "Abductive Reasoning": "가추적 추론",
        "Syllogism": "삼단논법",
        "Fallacy": "오류",
        "Ad Hominem": "인신 공격",
        "Straw Man": "허수아비 논증",
        "Categorical Imperative": "정언 명령",
        "Social Contract": "사회 계약",
        "State of Nature": "자연 상태",
        "Justice": "정의",
        "Liberty": "자유",
        "Equality": "평등",
        "Common Good": "공공선",
        "Forms": "이데아",
        "Substance": "실체",
        "Essence": "본질",
        "Existence": "실존",
        "Being": "존재",
        "Hermeneutics": "해석학",
        "Structuralism": "구조주의",
        "Post-structuralism": "후기 구조주의",
        "Deconstruction": "해체주의",
    },

    "Media & Communication": {
        **_POLITICS_SOCIETY,
        "Broadcasting": "방송",
        "Journalism": "저널리즘",
        "Media Literacy": "미디어 리터러시",
        "Framing": "프레이밍",
        "Agenda Setting": "의제 설정",
        "Public Relations": "홍보",
        "Propaganda": "선전",
        "Social Media": "소셜 미디어",
        "Audience": "수용자",
        "Content": "콘텐츠",
        "Narrative": "서사",
        "Discourse": "담론",
        "Convergence": "미디어 융합",
        "Digital Media": "디지털 미디어",
        "Censorship": "검열",
        "Freedom of Press": "언론 자유",
        "Fake News": "가짜 뉴스",
        "Influencer": "인플루언서",
        "Communication Theory": "커뮤니케이션 이론",
        "Encoding": "부호화",
        "Decoding": "해독",
        "Channel": "채널",
        "Noise": "잡음",
        "Feedback": "피드백",
        "Interpersonal Communication": "대인 커뮤니케이션",
        "Mass Communication": "대중 커뮤니케이션",
        "Nonverbal Communication": "비언어적 커뮤니케이션",
        "Semiotics": "기호학",
        "Signifier": "기표",
        "Signified": "기의",
        "Representation": "재현",
        "Cultural Studies": "문화 연구",
        "Media Effects": "미디어 효과",
        "Cultivation Theory": "배양 이론",
        "Uses and Gratifications": "이용과 충족",
        "Gatekeeping": "게이트키핑",
        "News Value": "뉴스 가치",
        "Objectivity": "객관성",
        "Crisis Communication": "위기 커뮤니케이션",
        "Net Neutrality": "망 중립성",
        "Algorithm": "알고리즘",
        "Filter Bubble": "필터 버블",
        "Echo Chamber": "반향실 효과",
        "Disinformation": "허위 정보",
        "Misinformation": "오정보",
        "Verification": "팩트체크",
        "Data Journalism": "데이터 저널리즘",
        "Podcast": "팟캐스트",
        "Streaming": "스트리밍",
        "User-generated Content": "사용자 제작 콘텐츠",
        "Viral Content": "바이럴 콘텐츠",
        "Transmedia": "트랜스미디어",
        "Participatory Culture": "참여 문화",
        "Crowdsourcing": "크라우드소싱",
        "Citizen Journalism": "시민 저널리즘",
        "Attention Economy": "주의 경제",
        "Clickbait": "클릭베이트",
        "Paywall": "페이월",
        "Copyright": "저작권",
        "Privacy": "프라이버시",
        "Surveillance": "감시",
    },

    "Political Science": {
        **_POLITICS_SOCIETY,
        "Political Science": "정치학",
        "Legislature": "입법부",
        "Executive": "행정부",
        "Judiciary": "사법부",
        "Separation of Powers": "삼권분립",
        "Federalism": "연방주의",
        "Constitution": "헌법",
        "Election": "선거",
        "Voting": "투표",
        "Political Party": "정당",
        "Lobbying": "로비",
        "Governance": "거버넌스",
        "Bureaucracy": "관료제",
        "Totalitarianism": "전체주의",
        "Populism": "포퓰리즘",
        "Communism": "공산주의",
        "Fascism": "파시즘",
        "Anarchism": "아나키즘",
        "Republicanism": "공화주의",
        "Social Democracy": "사회민주주의",
        "Neoliberalism": "신자유주의",
        "Political Ideology": "정치 이데올로기",
        "Legitimacy": "정당성",
        "Authority": "권위",
        "State": "국가",
        "Citizenship": "시민권",
        "Civil Rights": "시민권",
        "Rule of Law": "법의 지배",
        "Checks and Balances": "견제와 균형",
        "Electoral System": "선거 제도",
        "Proportional Representation": "비례대표제",
        "Gerrymandering": "선거구 획정 조작",
        "Turnout": "투표율",
        "Campaign": "선거 운동",
        "Political Participation": "정치 참여",
        "Interest Group": "이익 집단",
        "Think Tank": "싱크탱크",
        "Political Culture": "정치 문화",
        "Public Opinion": "여론",
        "Poll": "여론 조사",
        "Policy Making": "정책 결정",
        "Policy Implementation": "정책 집행",
        "Policy Evaluation": "정책 평가",
        "Coalition Government": "연립 정부",
        "Parliamentary System": "의원내각제",
        "Presidential System": "대통령제",
        "Decentralization": "분권화",
        "Local Government": "지방 정부",
        "Constitutional Court": "헌법 재판소",
        "Judicial Review": "사법 심사",
        "Identity Politics": "정체성 정치",
        "Oligarchy": "과두제",
        "Plutocracy": "금권정치",
        "Corruption": "부패",
        "Accountability": "책임성",
        "Transparency": "투명성",
        "Democratic Backsliding": "민주주의 후퇴",
        "Revolution": "혁명",
        "Coup d'état": "쿠데타",
    },

    "Food Science & Nutrition": {
        **_CHEMISTRY_BASE,
        **_BIO_MOLECULAR,
        "Food Science": "식품과학",
        "Nutrition": "영양학",
        "Macronutrient": "다량영양소",
        "Micronutrient": "미량영양소",
        "Carbohydrate": "탄수화물",
        "Fat": "지방",
        "Saturated Fat": "포화 지방",
        "Unsaturated Fat": "불포화 지방",
        "Trans Fat": "트랜스 지방",
        "Cholesterol": "콜레스테롤",
        "Vitamin": "비타민",
        "Mineral": "무기질",
        "Calcium": "칼슘",
        "Iron": "철분",
        "Sodium": "나트륨",
        "Potassium": "칼륨",
        "Dietary Fiber": "식이 섬유",
        "Caloric Intake": "열량 섭취",
        "Basal Metabolic Rate": "기초 대사율",
        "BMI": "체질량 지수",
        "Body Fat Percentage": "체지방률",
        "Malnutrition": "영양실조",
        "Obesity": "비만",
        "Eating Disorder": "섭식 장애",
        "Anorexia Nervosa": "신경성 식욕부진증",
        "Bulimia Nervosa": "신경성 폭식증",
        "Diabetes Diet": "당뇨 식이",
        "Glycemic Index": "혈당 지수",
        "Glycemic Load": "혈당 부하",
        "Food Pyramid": "식품 피라미드",
        "Dietary Reference Intake": "영양소 섭취 기준",
        "Recommended Dietary Allowance": "권장 섭취량",
        "Food Group": "식품군",
        "Food Composition": "식품 성분",
        "Food Labeling": "식품 표시",
        "Nutrition Facts": "영양 성분",
        "Food Safety": "식품 안전",
        "HACCP": "위해요소중점관리기준",
        "Food Hygiene": "식품 위생",
        "Foodborne Illness": "식중독",
        "Pathogen": "병원체",
        "Food Spoilage": "식품 부패",
        "Food Preservation": "식품 보존",
        "Pasteurization": "저온살균",
        "Sterilization": "멸균",
        "Fermentation": "발효",
        "Probiotic": "프로바이오틱스",
        "Prebiotic": "프리바이오틱스",
        "Functional Food": "기능성 식품",
        "Food Additive": "식품 첨가물",
        "Preservative": "보존료",
        "Antioxidant": "항산화제",
        "Food Allergy": "식품 알레르기",
        "Gluten": "글루텐",
        "Lactose Intolerance": "유당 불내증",
        "Vegan": "비건",
        "Vegetarian": "채식주의자",
        "Mediterranean Diet": "지중해 식단",
        "Ketogenic Diet": "케토제닉 식단",
        "Intermittent Fasting": "간헐적 단식",
        "Food Engineering": "식품 공학",
        "Shelf Life": "유통 기한",
        "Sensory Evaluation": "관능 평가",
        "Clinical Nutrition": "임상 영양",
        "Public Health Nutrition": "공중보건 영양",
        "Sports Nutrition": "스포츠 영양",
    },

    "Tourism & Hospitality": {
        **_BUSINESS_BASE,
        **_MARKETING_BASE,
        "Tourism": "관광",
        "Hospitality": "호스피탈리티",
        "Hotel Management": "호텔 경영",
        "Food and Beverage": "식음료",
        "Front Office": "프런트 오피스",
        "Housekeeping": "객실 관리",
        "Concierge": "컨시어지",
        "Guest Service": "고객 서비스",
        "Service Quality": "서비스 품질",
        "Guest Experience": "투숙객 경험",
        "Customer Satisfaction": "고객 만족",
        "Loyalty Program": "로열티 프로그램",
        "Revenue Management": "매출 관리",
        "RevPAR": "객실당 매출",
        "ADR": "평균 객실 요금",
        "Occupancy Rate": "객실 점유율",
        "MICE": "MICE(회의·인센티브·컨벤션·전시)",
        "Convention": "컨벤션",
        "Tour Operator": "투어 오퍼레이터",
        "Travel Agency": "여행사",
        "Inbound Tourism": "인바운드 관광",
        "Outbound Tourism": "아웃바운드 관광",
        "Domestic Tourism": "국내 관광",
        "Ecotourism": "에코투어",
        "Sustainable Tourism": "지속 가능 관광",
        "Cultural Tourism": "문화 관광",
        "Medical Tourism": "의료 관광",
        "Adventure Tourism": "어드벤처 관광",
        "Gastronomy Tourism": "미식 관광",
        "Wellness Tourism": "웰니스 관광",
        "Cruise Tourism": "크루즈 관광",
        "Heritage Site": "유산지",
        "UNESCO World Heritage": "유네스코 세계 유산",
        "Destination Marketing": "관광지 마케팅",
        "Visitor Management": "방문객 관리",
        "Carrying Capacity": "수용 용량",
        "Tourism Impact": "관광 영향",
        "Overtourism": "오버투어리즘",
        "Resort": "리조트",
        "Boutique Hotel": "부티크 호텔",
        "Hostel": "호스텔",
        "Shared Accommodation": "공유 숙박",
        "OTA": "온라인 여행사",
        "Reservation System": "예약 시스템",
        "Yield Management": "수익률 관리",
        "Banquet": "연회",
        "Catering": "케이터링",
        "Sommelier": "소믈리에",
        "Barista": "바리스타",
        "Restaurant Management": "레스토랑 경영",
        "Menu Engineering": "메뉴 엔지니어링",
        "Event Management": "이벤트 경영",
        "Festival Tourism": "축제 관광",
        "Travel Insurance": "여행 보험",
        "Tour Guide": "관광 가이드",
        "Itinerary": "여행 일정",
        "Visa": "비자",
        "Passport": "여권",
        "Theme Park": "테마파크",
        "Tourism Policy": "관광 정책",
        "Smart Tourism": "스마트 관광",
    },

    # ─────────────────────────────────────────────────────────────────
    # 예체능 (Arts & Sports)
    # ─────────────────────────────────────────────────────────────────

    "Fine Arts": {
        **_DESIGN_BASE,
        "Fine Arts": "미술",
        "Perspective": "원근법",
        "Chiaroscuro": "명암법",
        "Value": "명도",
        "Medium": "매체",
        "Canvas": "캔버스",
        "Pigment": "안료",
        "Impressionism": "인상주의",
        "Expressionism": "표현주의",
        "Abstract": "추상",
        "Figurative": "구상",
        "Portrait": "초상화",
        "Landscape": "풍경화",
        "Still Life": "정물화",
        "Sculpture": "조각",
        "Installation": "설치미술",
        "Critique": "비평",
        "Contour Line": "윤곽선",
        "Cross-hatching": "교차 해칭",
        "Shading": "명암 표현",
        "Color Wheel": "색상환",
        "Complementary Colors": "보색",
        "Warm Colors": "난색",
        "Cool Colors": "한색",
        "Monochromatic": "단색조",
        "Tint": "색조(흰색 혼합)",
        "Shade": "음영(검정 혼합)",
        "Tone": "중간 색조",
        "Fresco": "프레스코화",
        "Tempera": "템페라",
        "Watercolor": "수채화",
        "Oil Painting": "유화",
        "Acrylic": "아크릴화",
        "Printmaking": "판화",
        "Lithography": "석판화",
        "Etching": "에칭",
        "Screen Printing": "실크스크린",
        "Collage": "콜라주",
        "Mixed Media": "혼합 재료",
        "Photography": "사진",
        "Video Art": "비디오 아트",
        "Performance Art": "퍼포먼스 아트",
        "Conceptual Art": "개념 미술",
        "Street Art": "스트리트 아트",
        "Pop Art": "팝 아트",
        "Surrealism": "초현실주의",
        "Dadaism": "다다이즘",
        "Cubism": "입체주의",
        "Fauvism": "야수파",
        "Baroque": "바로크",
        "Renaissance": "르네상스",
        "Romanticism": "낭만주의",
        "Realism": "사실주의",
        "Minimalism": "미니멀리즘",
        "Contemporary Art": "현대 미술",
        "Curation": "큐레이션",
        "Gallery": "갤러리",
        "Exhibition": "전시",
        "Portfolio": "포트폴리오",
        "Auction": "경매",
        "Art History": "미술사",
        "Iconography": "도상학",
        "Public Art": "공공 미술",
        "Digital Art": "디지털 아트",
    },

    "Graphic Design": {
        **_DESIGN_BASE,
        "Graphic Design": "그래픽 디자인",
        "Grid": "그리드",
        "Hierarchy": "위계",
        "Alignment": "정렬",
        "White Space": "여백",
        "Color Theory": "색채 이론",
        "Brand Identity": "브랜드 아이덴티티",
        "Logo": "로고",
        "Icon": "아이콘",
        "Vector": "벡터",
        "Raster": "래스터",
        "Resolution": "해상도",
        "CMYK": "CMYK(인쇄 색상 모드)",
        "RGB": "RGB(화면 색상 모드)",
        "Mockup": "목업",
        "User Interface": "사용자 인터페이스",
        "User Experience": "사용자 경험",
        "Typeface": "서체",
        "Font": "폰트",
        "Serif": "세리프",
        "Sans-serif": "산세리프",
        "Kerning": "자간 조정",
        "Leading": "행간",
        "Legibility": "가독성",
        "Body Text": "본문 텍스트",
        "Display Type": "제목 서체",
        "Brightness": "밝기",
        "Opacity": "불투명도",
        "Layer": "레이어",
        "Mask": "마스크",
        "Stroke": "획",
        "Fill": "채우기",
        "Gradient": "그라데이션",
        "Infographic": "인포그래픽",
        "Data Visualization": "데이터 시각화",
        "Illustration": "일러스트레이션",
        "Art Direction": "아트 디렉션",
        "Creative Brief": "크리에이티브 브리프",
        "Mood Board": "무드보드",
        "Style Guide": "스타일 가이드",
        "Brand Book": "브랜드 북",
        "Print Design": "인쇄 디자인",
        "Editorial Design": "에디토리얼 디자인",
        "Packaging Design": "패키지 디자인",
        "Signage": "사이니지",
        "Motion Graphics": "모션 그래픽",
        "Animation": "애니메이션",
        "Storyboard": "스토리보드",
        "Responsive Design": "반응형 디자인",
        "Wireframe": "와이어프레임",
        "Design System": "디자인 시스템",
        "Accessibility": "접근성",
        "DPI": "DPI(인치당 픽셀 수)",
        "Bleed": "재단 여분",
        "Golden Ratio": "황금 비율",
    },

    "Industrial Design": {
        **_DESIGN_BASE,
        "Industrial Design": "산업 디자인",
        "Ergonomics": "인체공학",
        "Form": "형태",
        "Function": "기능",
        "Material": "소재",
        "Manufacturing Process": "제조 공정",
        "Sustainability": "지속 가능성",
        "User-centered Design": "사용자 중심 설계",
        "Ideation": "아이디어 발상",
        "3D Modeling": "3D 모델링",
        "CAD": "컴퓨터 지원 설계",
        "Product Lifecycle": "제품 수명 주기",
        "Usability": "사용성",
        "Tolerance": "공차",
        "Assembly": "조립",
        "Injection Molding": "사출 성형",
        "Design Thinking": "디자인 씽킹",
        "Empathize": "공감",
        "Concept Development": "개념 개발",
        "Design Brief": "디자인 브리프",
        "User Research": "사용자 연구",
        "Persona": "페르소나",
        "Storyboard": "스토리보드",
        "CNC Machining": "CNC 가공",
        "3D Printing": "3D 프린팅",
        "Rapid Prototyping": "신속 시제품 제작",
        "Mold": "금형",
        "Finishing": "표면 처리",
        "CMF Design": "CMF 디자인(색상·소재·표면처리)",
        "Plastic": "플라스틱",
        "Metal": "금속",
        "Composite": "복합 소재",
        "Bioplastic": "바이오 플라스틱",
        "Recyclability": "재활용 가능성",
        "Upcycling": "업사이클링",
        "Life Cycle Assessment": "생애 주기 평가",
        "Anthropometry": "인체 측정학",
        "Affordance": "어포던스",
        "Mental Model": "멘탈 모델",
        "Design Language": "디자인 언어",
        "Form Factor": "폼 팩터",
        "Universal Design": "유니버설 디자인",
        "Inclusive Design": "포용적 디자인",
        "Design Patent": "디자인 특허",
        "Service Design": "서비스 디자인",
        "Interaction Design": "인터랙션 디자인",
        "Wearable Technology": "웨어러블 기술",
        "Internet of Things": "사물 인터넷",
        "Smart Product": "스마트 제품",
        "Circular Economy": "순환 경제",
    },

    "Music Composition": {
        "Music Composition": "음악 작곡",
        "Harmony": "화성",
        "Melody": "선율",
        "Rhythm": "리듬",
        "Tempo": "빠르기",
        "Dynamics": "강약",
        "Timbre": "음색",
        "Counterpoint": "대위법",
        "Chord": "화음",
        "Scale": "음계",
        "Key Signature": "조표",
        "Time Signature": "박자표",
        "Modulation": "전조",
        "Cadence": "종지",
        "Motif": "동기",
        "Theme": "주제",
        "Variation": "변주",
        "Orchestration": "관현악법",
        "Notation": "악보 표기",
        "Polyphony": "다성음악",
        "Homophony": "단성 화성 음악",
        "Monophony": "단성음악",
        "Atonality": "무조성",
        "Tonality": "조성",
        "Tonic": "으뜸음",
        "Dominant": "딸림음",
        "Triad": "3화음",
        "Seventh Chord": "7화음",
        "Voice Leading": "성부 진행",
        "Dissonance": "불협화음",
        "Consonance": "협화음",
        "Ostinato": "오스티나토",
        "Canon": "카논",
        "Fugue": "푸가",
        "Sonata Form": "소나타 형식",
        "Rondo Form": "론도 형식",
        "Binary Form": "2부 형식",
        "Ternary Form": "3부 형식",
        "Exposition": "제시부",
        "Development": "발전부",
        "Recapitulation": "재현부",
        "Coda": "코다",
        "Bridge": "교량 악절",
        "Phrase": "악구",
        "Period": "악절",
        "Piano": "여리게(p)",
        "Forte": "세게(f)",
        "Crescendo": "점점 세게",
        "Decrescendo": "점점 여리게",
        "Staccato": "스타카토",
        "Legato": "레가토",
        "Vibrato": "비브라토",
        "Trill": "트릴",
        "Fermata": "페르마타",
        "Ritardando": "점점 느리게",
        "Accelerando": "점점 빠르게",
        "Rubato": "루바토",
        "Program Music": "표제 음악",
        "Absolute Music": "절대 음악",
        "Leitmotif": "라이트모티프",
        "Electronic Music": "전자 음악",
        "Sampling": "샘플링",
        "DAW": "디지털 오디오 워크스테이션",
        "MIDI": "MIDI(악기 디지털 인터페이스)",
        "Mixing": "믹싱",
        "Mastering": "마스터링",
        "Arrangement": "편곡",
        "Score": "총보",
        "Transposition": "조 바꿈",
        "Syncopation": "당김음",
    },

    "Vocal Music": {
        "Vocal Music": "성악",
        "Soprano": "소프라노",
        "Mezzo-soprano": "메조소프라노",
        "Alto": "알토",
        "Contralto": "콘트랄토",
        "Tenor": "테너",
        "Baritone": "바리톤",
        "Bass": "베이스",
        "Countertenor": "카운터테너",
        "Voice Type": "성종",
        "Vocal Range": "음역",
        "Tessitura": "테시투라",
        "Falsetto": "팔세토",
        "Head Voice": "두성",
        "Chest Voice": "흉성",
        "Mixed Voice": "믹스 보이스",
        "Whistle Register": "휘슬 레지스터",
        "Vocal Cords": "성대",
        "Larynx": "후두",
        "Diaphragm": "횡격막",
        "Breath Support": "호흡 지지",
        "Breath Control": "호흡 조절",
        "Vocal Resonance": "공명",
        "Vocal Placement": "발성 위치",
        "Vocal Technique": "발성 기법",
        "Vocal Warm-up": "발성 준비 운동",
        "Vocal Exercise": "발성 연습",
        "Vocal Coach": "보컬 코치",
        "Vibrato": "비브라토",
        "Legato": "레가토",
        "Staccato": "스타카토",
        "Trill": "트릴",
        "Melisma": "멜리스마",
        "Coloratura": "콜로라투라",
        "Bel Canto": "벨칸토",
        "Aria": "아리아",
        "Recitative": "레치타티보",
        "Cadenza": "카덴차",
        "Cabaletta": "카발레타",
        "Opera": "오페라",
        "Operetta": "오페레타",
        "Lieder": "예술가곡",
        "Art Song": "예술 가곡",
        "Chanson": "샹송",
        "Oratorio": "오라토리오",
        "Cantata": "칸타타",
        "Musical Theatre": "뮤지컬",
        "Chorus": "합창",
        "Choir": "성가대",
        "Choral Music": "합창 음악",
        "A cappella": "아카펠라",
        "Madrigal": "마드리갈",
        "Mass": "미사곡",
        "Requiem": "레퀴엠",
        "Diction": "딕션(발음법)",
        "Pronunciation": "발음",
        "Articulation": "발음 명료도",
        "IPA": "국제 음성 기호",
        "Italian Diction": "이탈리아어 딕션",
        "German Diction": "독일어 딕션",
        "French Diction": "프랑스어 딕션",
        "Latin Diction": "라틴어 딕션",
        "Phrasing": "프레이징",
        "Dynamics": "강약",
        "Crescendo": "점점 세게",
        "Decrescendo": "점점 여리게",
        "Pitch": "음정",
        "Tone Quality": "음질",
        "Timbre": "음색",
        "Range Expansion": "음역 확장",
        "Audition": "오디션",
        "Repertoire": "레퍼토리",
        "Score Reading": "악보 읽기",
        "Sight-singing": "초견",
        "Ear Training": "청음 훈련",
        "Solfege": "솔페지",
        "Performance Practice": "연주 관행",
        "Stage Presence": "무대 매너",
        "Microphone Technique": "마이크 기법",
    },

    "Physical Education": {
        "Physical Education": "체육학",
        "Cardiovascular Endurance": "심폐 지구력",
        "Muscular Strength": "근력",
        "Flexibility": "유연성",
        "Agility": "민첩성",
        "Coordination": "협응력",
        "Training": "훈련",
        "Aerobic": "유산소",
        "Anaerobic": "무산소",
        "Metabolism": "대사",
        "Nutrition": "영양",
        "Injury Prevention": "부상 예방",
        "Biomechanics": "생체역학",
        "Motor Learning": "운동 학습",
        "Periodization": "기간화 훈련",
        "Recovery": "회복",
        "Sports Psychology": "스포츠 심리학",
        "Tactics": "전술",
        "Fair Play": "페어플레이",
        "Performance Analysis": "퍼포먼스 분석",
        "Warm-up": "준비 운동",
        "Cool-down": "정리 운동",
        "Stretching": "스트레칭",
        "Resistance Training": "저항 훈련",
        "Plyometrics": "플라이오메트릭스",
        "HIIT": "고강도 인터벌 훈련",
        "Circuit Training": "서킷 트레이닝",
        "Interval Training": "인터벌 트레이닝",
        "Progressive Overload": "점진적 과부하",
        "Overtraining": "과훈련",
        "Tapering": "테이퍼링",
        "Muscle Hypertrophy": "근육 비대",
        "Fast-twitch Fiber": "속근 섬유",
        "Slow-twitch Fiber": "지근 섬유",
        "VO2 Max": "최대 산소 섭취량",
        "Lactate Threshold": "젖산 역치",
        "Heart Rate": "심박수",
        "RPE Scale": "운동 자각도",
        "Body Composition": "신체 구성",
        "BMI": "체질량 지수",
        "Body Fat Percentage": "체지방률",
        "Lean Body Mass": "제지방 체중",
        "Caloric Expenditure": "칼로리 소모",
        "ATP-PC System": "ATP-PC 시스템",
        "DOMS": "지연성 근육통",
        "RICE Method": "RICE 처치법",
        "Sports Medicine": "스포츠 의학",
        "Physical Therapy": "물리 치료",
        "Kinesiology": "운동학",
        "Power": "파워",
        "Speed": "속도",
        "Reaction Time": "반응 시간",
        "Endurance": "지구력",
        "Stamina": "체력",
        "Physical Fitness": "체력",
        "Goal Setting": "목표 설정",
        "Visualization": "심상 훈련",
        "Doping": "도핑",
        "Adaptive Sports": "장애인 스포츠",
        "Paralympic": "패럴림픽",
        "Exercise Physiology": "운동 생리학",
        "Functional Movement": "기능적 움직임",
        "Proprioception": "고유 수용성 감각",
    },

    "Film & Digital Media": {
        **_DESIGN_BASE,
        "Film": "영화",
        "Cinematography": "촬영술",
        "Editing": "편집",
        "Narrative": "서사",
        "Screenplay": "시나리오",
        "Direction": "연출",
        "Mise-en-scène": "미장센",
        "Montage": "몽타주",
        "Storyboard": "스토리보드",
        "Post-production": "후반 작업",
        "Visual Effects": "시각 효과",
        "Sound Design": "음향 디자인",
        "Color Grading": "색 보정",
        "Documentary": "다큐멘터리",
        "Genre": "장르",
        "Auteur": "작가주의",
        "Distribution": "배급",
        "Streaming": "스트리밍",
        "Frame Rate": "프레임 속도",
        "Resolution": "해상도",
        "Shot": "쇼트",
        "Scene": "씬",
        "Sequence": "시퀀스",
        "Cut": "컷",
        "Continuity Editing": "연속성 편집",
        "Jump Cut": "점프 컷",
        "Cross-cutting": "교차 편집",
        "Match Cut": "매치 컷",
        "Fade": "페이드",
        "Dissolve": "디졸브",
        "Long Shot": "롱 쇼트",
        "Medium Shot": "미디엄 쇼트",
        "Close-up": "클로즈업",
        "Establishing Shot": "설정 쇼트",
        "Point of View Shot": "시점 쇼트",
        "Over-the-shoulder Shot": "오버 더 숄더 쇼트",
        "Pan": "팬",
        "Tilt": "틸트",
        "Dolly": "달리",
        "Tracking Shot": "트래킹 쇼트",
        "Handheld": "핸드헬드",
        "Steadicam": "스테디캠",
        "Drone Shot": "드론 쇼트",
        "Depth of Field": "피사계 심도",
        "Shallow Focus": "얕은 초점",
        "Deep Focus": "깊은 초점",
        "Aperture": "조리개",
        "Shutter Speed": "셔터 속도",
        "ISO": "감도",
        "Lighting": "조명",
        "Three-point Lighting": "3점 조명",
        "Key Light": "주조명",
        "Fill Light": "보조 조명",
        "Back Light": "역광 조명",
        "Production Design": "미술 설계",
        "Costume Design": "의상 디자인",
        "Casting": "캐스팅",
        "Acting": "연기",
        "Method Acting": "메소드 연기",
        "ADR": "후시 녹음",
        "Foley": "폴리(효과음 제작)",
        "Soundtrack": "사운드트랙",
        "VFX": "시각 효과",
        "CGI": "컴퓨터 그래픽 이미지",
        "Green Screen": "그린스크린",
        "Motion Capture": "모션 캡처",
        "Independent Film": "독립 영화",
        "Blockbuster": "블록버스터",
        "Film Festival": "영화제",
        "Protagonist": "주인공",
        "Antagonist": "악당",
        "Character Arc": "캐릭터 아크",
    },

    "Fashion Design": {
        **_DESIGN_BASE,
        "Fashion Design": "패션 디자인",
        "Silhouette": "실루엣",
        "Draping": "드레이핑",
        "Textile": "직물",
        "Pattern Making": "패턴 제작",
        "Haute Couture": "오트 쿠튀르",
        "Ready-to-Wear": "기성복",
        "Trend": "트렌드",
        "Collection": "컬렉션",
        "Mood Board": "무드보드",
        "Lookbook": "룩북",
        "Sustainability": "지속 가능성",
        "Upcycling": "업사이클링",
        "Brand Identity": "브랜드 아이덴티티",
        "Sewing": "봉제",
        "Seam": "솔기",
        "Hem": "단",
        "Runway": "런웨이",
        "Fashion Week": "패션 위크",
        "Flat Drawing": "플랫 도식화",
        "Technical Drawing": "테크니컬 드로잉",
        "Muslin": "머슬린",
        "Fitting": "가봉",
        "Dart": "다트",
        "Pleat": "플리트",
        "Lining": "안감",
        "Zipper": "지퍼",
        "Bias Cut": "바이어스 재단",
        "Weave": "직조",
        "Knit": "니트",
        "Woven": "우븐",
        "Natural Fiber": "천연 섬유",
        "Synthetic Fiber": "합성 섬유",
        "Cotton": "면",
        "Wool": "모",
        "Silk": "실크",
        "Linen": "린넨",
        "Polyester": "폴리에스터",
        "Nylon": "나일론",
        "Leather": "가죽",
        "Denim": "데님",
        "Chiffon": "시폰",
        "Velvet": "벨벳",
        "Satin": "새틴",
        "Tweed": "트위드",
        "Dye": "염색",
        "Print": "프린트",
        "Embroidery": "자수",
        "Fashion Forecasting": "패션 예측",
        "Fast Fashion": "패스트 패션",
        "Slow Fashion": "슬로 패션",
        "Vintage": "빈티지",
        "Circular Fashion": "순환 패션",
        "Fashion Merchandising": "패션 머천다이징",
        "Visual Merchandising": "비주얼 머천다이징",
        "Fashion Photography": "패션 사진",
        "Styling": "스타일링",
        "Accessory": "액세서리",
        "Activewear": "액티브웨어",
        "Menswear": "남성복",
        "Womenswear": "여성복",
        "Gender-neutral Fashion": "젠더 뉴트럴 패션",
        "Sustainable Textile": "지속 가능 섬유",
    },
}
